# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'control_panel.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1050, 776)
        MainWindow.setStyleSheet("")
        self.control_window = QtWidgets.QWidget(MainWindow)
        self.control_window.setStyleSheet("QWidget {\n"
"    background-color: rgb(56, 57, 60);\n"
"}\n"
"\n"
"\n"
"QFrame {\n"
"    background-color: rgb(86, 88, 93);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"\n"
"QPushButton {\n"
"    background-color: rgb(114, 159, 207);\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:disabled {\n"
"    color: gray;\n"
"    background-color: rgb(86, 88, 93);\n"
"}\n"
"QPushButton:pressed {\n"
"    color: rgb(86, 88, 93);\n"
"    background-color: rgb(138, 226, 52);\n"
"}\n"
"\n"
"\n"
"QStackedWidget > QWidget {\n"
"    background-color: rgb(86, 88, 93);\n"
"    border-radius: 10px;\n"
"}\n"
"QStackedWidget QLabel {\n"
"    color: white;\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"}\n"
"QStackedWidget QLabel:disabled {\n"
"    color: gray;\n"
"}\n"
"\n"
"QStackedWidget QPushButton {\n"
"    background-color: rgb(114, 159, 207);\n"
"    font-size: 25px;\n"
"}\n"
"\n"
"QStackedWidget QRadioButton:disabled {\n"
"    font-size: 20px;\n"
"    color: gray;\n"
"    font-weight: bold;\n"
"    background-color: rgb(86, 88, 93);\n"
"}\n"
"QStackedWidget QRadioButton {\n"
"    font-size: 20px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    background-color: rgb(86, 88, 93);\n"
"}\n"
"\n"
"QStackedWidget QLineEdit {\n"
"    font-size: 20px;\n"
"    color: white;\n"
"    background-color: rgb(86, 88, 93);\n"
"}\n"
"\n"
"QStackedWidget QGroupBox {\n"
"    font-size: 20px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    background-color: rgb(86, 88, 93);\n"
"}\n"
"QStackedWidget QGroupBox:disabled {\n"
"    color: gray;\n"
"}\n"
"\n"
"QStackedWidget QComboBox {\n"
"    color: white;\n"
"    background-color: rgb(114, 159, 207);\n"
"    font-size: 25px;\n"
"    font-weight: bold;\n"
"    border-radius: 10px;\n"
"}\n"
"QStackedWidget QComboBox:disabled {\n"
"    background-color: rgb(86, 88, 93);\n"
"    color: gray;\n"
"}\n"
"\n"
"QStackedWidget QTextBrowser {\n"
"    color: white;\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"QSlider{\n"
"    \n"
"    background-color: rgb(138, 226, 52);\n"
"}")
        self.control_window.setObjectName("control_window")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.control_window)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.control_window)
        self.frame_2.setEnabled(True)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.pg_init = QtWidgets.QWidget()
        self.pg_init.setObjectName("pg_init")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.pg_init)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.group_init = QtWidgets.QGroupBox(self.pg_init)
        self.group_init.setObjectName("group_init")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.group_init)
        self.horizontalLayout_2.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.bx_rate0 = QtWidgets.QComboBox(self.group_init)
        self.bx_rate0.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bx_rate0.sizePolicy().hasHeightForWidth())
        self.bx_rate0.setSizePolicy(sizePolicy)
        self.bx_rate0.setObjectName("bx_rate0")
        self.bx_rate0.addItem("")
        self.verticalLayout_4.addWidget(self.bx_rate0)
        self.bx_rate1 = QtWidgets.QComboBox(self.group_init)
        self.bx_rate1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bx_rate1.sizePolicy().hasHeightForWidth())
        self.bx_rate1.setSizePolicy(sizePolicy)
        self.bx_rate1.setObjectName("bx_rate1")
        self.bx_rate1.addItem("")
        self.verticalLayout_4.addWidget(self.bx_rate1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.bt_open_device = QtWidgets.QPushButton(self.group_init)
        self.bt_open_device.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_open_device.sizePolicy().hasHeightForWidth())
        self.bt_open_device.setSizePolicy(sizePolicy)
        self.bt_open_device.setObjectName("bt_open_device")
        self.horizontalLayout_2.addWidget(self.bt_open_device)
        self.bt_init_motor = QtWidgets.QPushButton(self.group_init)
        self.bt_init_motor.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_init_motor.sizePolicy().hasHeightForWidth())
        self.bt_init_motor.setSizePolicy(sizePolicy)
        self.bt_init_motor.setObjectName("bt_init_motor")
        self.horizontalLayout_2.addWidget(self.bt_init_motor)
        self.frame_7 = QtWidgets.QFrame(self.group_init)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.motor_check_1 = QtWidgets.QLabel(self.frame_7)
        self.motor_check_1.setAlignment(QtCore.Qt.AlignCenter)
        self.motor_check_1.setIndent(-1)
        self.motor_check_1.setObjectName("motor_check_1")
        self.verticalLayout_2.addWidget(self.motor_check_1)
        self.motor_check_2 = QtWidgets.QLabel(self.frame_7)
        self.motor_check_2.setAlignment(QtCore.Qt.AlignCenter)
        self.motor_check_2.setIndent(-1)
        self.motor_check_2.setObjectName("motor_check_2")
        self.verticalLayout_2.addWidget(self.motor_check_2)
        self.horizontalLayout_2.addWidget(self.frame_7)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 2)
        self.horizontalLayout_2.setStretch(2, 2)
        self.horizontalLayout_2.setStretch(3, 2)
        self.verticalLayout_7.addWidget(self.group_init)
        self.group_status_control = QtWidgets.QGroupBox(self.pg_init)
        self.group_status_control.setEnabled(True)
        self.group_status_control.setObjectName("group_status_control")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.group_status_control)
        self.verticalLayout_13.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_13.setSpacing(10)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_5 = QtWidgets.QFrame(self.group_status_control)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(10)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.frame_8 = QtWidgets.QFrame(self.frame_5)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(10)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.bt_shut_down = QtWidgets.QPushButton(self.frame_8)
        self.bt_shut_down.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_shut_down.sizePolicy().hasHeightForWidth())
        self.bt_shut_down.setSizePolicy(sizePolicy)
        self.bt_shut_down.setObjectName("bt_shut_down")
        self.horizontalLayout_13.addWidget(self.bt_shut_down)
        self.bt_switch_on = QtWidgets.QPushButton(self.frame_8)
        self.bt_switch_on.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_switch_on.sizePolicy().hasHeightForWidth())
        self.bt_switch_on.setSizePolicy(sizePolicy)
        self.bt_switch_on.setObjectName("bt_switch_on")
        self.horizontalLayout_13.addWidget(self.bt_switch_on)
        self.bt_enable_operation = QtWidgets.QPushButton(self.frame_8)
        self.bt_enable_operation.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_enable_operation.sizePolicy().hasHeightForWidth())
        self.bt_enable_operation.setSizePolicy(sizePolicy)
        self.bt_enable_operation.setObjectName("bt_enable_operation")
        self.horizontalLayout_13.addWidget(self.bt_enable_operation)
        self.verticalLayout_19.addWidget(self.frame_8)
        self.frame_13 = QtWidgets.QFrame(self.frame_5)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setSpacing(10)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.bt_disable_voltage = QtWidgets.QPushButton(self.frame_13)
        self.bt_disable_voltage.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_disable_voltage.sizePolicy().hasHeightForWidth())
        self.bt_disable_voltage.setSizePolicy(sizePolicy)
        self.bt_disable_voltage.setObjectName("bt_disable_voltage")
        self.horizontalLayout_23.addWidget(self.bt_disable_voltage)
        self.bt_disable_operation = QtWidgets.QPushButton(self.frame_13)
        self.bt_disable_operation.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_disable_operation.sizePolicy().hasHeightForWidth())
        self.bt_disable_operation.setSizePolicy(sizePolicy)
        self.bt_disable_operation.setObjectName("bt_disable_operation")
        self.horizontalLayout_23.addWidget(self.bt_disable_operation)
        self.bt_quick_stop = QtWidgets.QPushButton(self.frame_13)
        self.bt_quick_stop.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_quick_stop.sizePolicy().hasHeightForWidth())
        self.bt_quick_stop.setSizePolicy(sizePolicy)
        self.bt_quick_stop.setObjectName("bt_quick_stop")
        self.horizontalLayout_23.addWidget(self.bt_quick_stop)
        self.verticalLayout_19.addWidget(self.frame_13)
        self.frame_4 = QtWidgets.QFrame(self.frame_5)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.bt_fault_reset = QtWidgets.QPushButton(self.frame_4)
        self.bt_fault_reset.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_fault_reset.sizePolicy().hasHeightForWidth())
        self.bt_fault_reset.setSizePolicy(sizePolicy)
        self.bt_fault_reset.setObjectName("bt_fault_reset")
        self.horizontalLayout_3.addWidget(self.bt_fault_reset)
        self.verticalLayout_19.addWidget(self.frame_4)
        self.verticalLayout_13.addWidget(self.frame_5)
        self.verticalLayout_7.addWidget(self.group_status_control)
        self.group_param = QtWidgets.QGroupBox(self.pg_init)
        self.group_param.setEnabled(True)
        self.group_param.setObjectName("group_param")
        self.verticalLayout_98 = QtWidgets.QVBoxLayout(self.group_param)
        self.verticalLayout_98.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_98.setSpacing(0)
        self.verticalLayout_98.setObjectName("verticalLayout_98")
        self.frame_40 = QtWidgets.QFrame(self.group_param)
        self.frame_40.setObjectName("frame_40")
        self.verticalLayout_99 = QtWidgets.QVBoxLayout(self.frame_40)
        self.verticalLayout_99.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_99.setSpacing(0)
        self.verticalLayout_99.setObjectName("verticalLayout_99")
        self.frame_41 = QtWidgets.QFrame(self.frame_40)
        self.frame_41.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_41.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_41.setObjectName("frame_41")
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout(self.frame_41)
        self.horizontalLayout_46.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_46.setSpacing(7)
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.verticalLayout_100 = QtWidgets.QVBoxLayout()
        self.verticalLayout_100.setContentsMargins(15, -1, 15, -1)
        self.verticalLayout_100.setSpacing(0)
        self.verticalLayout_100.setObjectName("verticalLayout_100")
        self.type_t = QtWidgets.QRadioButton(self.frame_41)
        self.type_t.setEnabled(True)
        self.type_t.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.type_t.setCheckable(True)
        self.type_t.setChecked(True)
        self.type_t.setObjectName("type_t")
        self.verticalLayout_100.addWidget(self.type_t)
        self.type_s = QtWidgets.QRadioButton(self.frame_41)
        self.type_s.setEnabled(True)
        self.type_s.setChecked(False)
        self.type_s.setObjectName("type_s")
        self.verticalLayout_100.addWidget(self.type_s)
        self.horizontalLayout_46.addLayout(self.verticalLayout_100)
        self.verticalLayout_101 = QtWidgets.QVBoxLayout()
        self.verticalLayout_101.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_101.setSpacing(10)
        self.verticalLayout_101.setObjectName("verticalLayout_101")
        self.tx_acc = QtWidgets.QLabel(self.frame_41)
        self.tx_acc.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_acc.sizePolicy().hasHeightForWidth())
        self.tx_acc.setSizePolicy(sizePolicy)
        self.tx_acc.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_acc.setObjectName("tx_acc")
        self.verticalLayout_101.addWidget(self.tx_acc)
        self.le_acc = QtWidgets.QLineEdit(self.frame_41)
        self.le_acc.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_acc.sizePolicy().hasHeightForWidth())
        self.le_acc.setSizePolicy(sizePolicy)
        self.le_acc.setAlignment(QtCore.Qt.AlignCenter)
        self.le_acc.setObjectName("le_acc")
        self.verticalLayout_101.addWidget(self.le_acc)
        self.horizontalLayout_46.addLayout(self.verticalLayout_101)
        self.verticalLayout_102 = QtWidgets.QVBoxLayout()
        self.verticalLayout_102.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_102.setSpacing(10)
        self.verticalLayout_102.setObjectName("verticalLayout_102")
        self.tx_dec = QtWidgets.QLabel(self.frame_41)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_dec.sizePolicy().hasHeightForWidth())
        self.tx_dec.setSizePolicy(sizePolicy)
        self.tx_dec.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_dec.setObjectName("tx_dec")
        self.verticalLayout_102.addWidget(self.tx_dec)
        self.le_dec = QtWidgets.QLineEdit(self.frame_41)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_dec.sizePolicy().hasHeightForWidth())
        self.le_dec.setSizePolicy(sizePolicy)
        self.le_dec.setAlignment(QtCore.Qt.AlignCenter)
        self.le_dec.setObjectName("le_dec")
        self.verticalLayout_102.addWidget(self.le_dec)
        self.horizontalLayout_46.addLayout(self.verticalLayout_102)
        self.verticalLayout_103 = QtWidgets.QVBoxLayout()
        self.verticalLayout_103.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_103.setSpacing(10)
        self.verticalLayout_103.setObjectName("verticalLayout_103")
        self.tx_quick = QtWidgets.QLabel(self.frame_41)
        self.tx_quick.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_quick.sizePolicy().hasHeightForWidth())
        self.tx_quick.setSizePolicy(sizePolicy)
        self.tx_quick.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_quick.setObjectName("tx_quick")
        self.verticalLayout_103.addWidget(self.tx_quick)
        self.le_quick = QtWidgets.QLineEdit(self.frame_41)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_quick.sizePolicy().hasHeightForWidth())
        self.le_quick.setSizePolicy(sizePolicy)
        self.le_quick.setAlignment(QtCore.Qt.AlignCenter)
        self.le_quick.setObjectName("le_quick")
        self.verticalLayout_103.addWidget(self.le_quick)
        self.horizontalLayout_46.addLayout(self.verticalLayout_103)
        self.verticalLayout_104 = QtWidgets.QVBoxLayout()
        self.verticalLayout_104.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_104.setSpacing(10)
        self.verticalLayout_104.setObjectName("verticalLayout_104")
        self.tx_inhibit = QtWidgets.QLabel(self.frame_41)
        self.tx_inhibit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_inhibit.sizePolicy().hasHeightForWidth())
        self.tx_inhibit.setSizePolicy(sizePolicy)
        self.tx_inhibit.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_inhibit.setObjectName("tx_inhibit")
        self.verticalLayout_104.addWidget(self.tx_inhibit)
        self.le_inhibit = QtWidgets.QLineEdit(self.frame_41)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_inhibit.sizePolicy().hasHeightForWidth())
        self.le_inhibit.setSizePolicy(sizePolicy)
        self.le_inhibit.setAlignment(QtCore.Qt.AlignCenter)
        self.le_inhibit.setObjectName("le_inhibit")
        self.verticalLayout_104.addWidget(self.le_inhibit)
        self.horizontalLayout_46.addLayout(self.verticalLayout_104)
        self.verticalLayout_105 = QtWidgets.QVBoxLayout()
        self.verticalLayout_105.setSpacing(10)
        self.verticalLayout_105.setObjectName("verticalLayout_105")
        self.bt_save = QtWidgets.QPushButton(self.frame_41)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_save.sizePolicy().hasHeightForWidth())
        self.bt_save.setSizePolicy(sizePolicy)
        self.bt_save.setObjectName("bt_save")
        self.verticalLayout_105.addWidget(self.bt_save)
        self.bt_launch = QtWidgets.QPushButton(self.frame_41)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_launch.sizePolicy().hasHeightForWidth())
        self.bt_launch.setSizePolicy(sizePolicy)
        self.bt_launch.setObjectName("bt_launch")
        self.verticalLayout_105.addWidget(self.bt_launch)
        self.horizontalLayout_46.addLayout(self.verticalLayout_105)
        self.horizontalLayout_46.setStretch(0, 2)
        self.horizontalLayout_46.setStretch(1, 2)
        self.horizontalLayout_46.setStretch(2, 2)
        self.horizontalLayout_46.setStretch(3, 2)
        self.horizontalLayout_46.setStretch(4, 2)
        self.horizontalLayout_46.setStretch(5, 3)
        self.verticalLayout_99.addWidget(self.frame_41)
        self.verticalLayout_98.addWidget(self.frame_40)
        self.verticalLayout_7.addWidget(self.group_param)
        self.group_motor_control = QtWidgets.QFrame(self.pg_init)
        self.group_motor_control.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.group_motor_control.setFrameShadow(QtWidgets.QFrame.Raised)
        self.group_motor_control.setObjectName("group_motor_control")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.group_motor_control)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.group_param_modify_6 = QtWidgets.QGroupBox(self.group_motor_control)
        self.group_param_modify_6.setEnabled(True)
        self.group_param_modify_6.setObjectName("group_param_modify_6")
        self.verticalLayout_109 = QtWidgets.QVBoxLayout(self.group_param_modify_6)
        self.verticalLayout_109.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_109.setSpacing(0)
        self.verticalLayout_109.setObjectName("verticalLayout_109")
        self.frame_44 = QtWidgets.QFrame(self.group_param_modify_6)
        self.frame_44.setObjectName("frame_44")
        self.verticalLayout_110 = QtWidgets.QVBoxLayout(self.frame_44)
        self.verticalLayout_110.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_110.setSpacing(0)
        self.verticalLayout_110.setObjectName("verticalLayout_110")
        self.frame_45 = QtWidgets.QFrame(self.frame_44)
        self.frame_45.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_45.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_45.setObjectName("frame_45")
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout(self.frame_45)
        self.horizontalLayout_48.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_48.setSpacing(10)
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.verticalLayout_56 = QtWidgets.QVBoxLayout()
        self.verticalLayout_56.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_56.setSpacing(10)
        self.verticalLayout_56.setObjectName("verticalLayout_56")
        self.bt_lock = QtWidgets.QPushButton(self.frame_45)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_lock.sizePolicy().hasHeightForWidth())
        self.bt_lock.setSizePolicy(sizePolicy)
        self.bt_lock.setObjectName("bt_lock")
        self.verticalLayout_56.addWidget(self.bt_lock)
        self.bt_adaptive = QtWidgets.QPushButton(self.frame_45)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_adaptive.sizePolicy().hasHeightForWidth())
        self.bt_adaptive.setSizePolicy(sizePolicy)
        self.bt_adaptive.setObjectName("bt_adaptive")
        self.verticalLayout_56.addWidget(self.bt_adaptive)
        self.verticalLayout_56.setStretch(0, 1)
        self.verticalLayout_56.setStretch(1, 1)
        self.horizontalLayout_48.addLayout(self.verticalLayout_56)
        self.horizontalLayout_48.setStretch(0, 1)
        self.verticalLayout_110.addWidget(self.frame_45)
        self.verticalLayout_109.addWidget(self.frame_44)
        self.horizontalLayout_4.addWidget(self.group_param_modify_6)
        self.group_param_modify_5 = QtWidgets.QGroupBox(self.group_motor_control)
        self.group_param_modify_5.setEnabled(True)
        self.group_param_modify_5.setObjectName("group_param_modify_5")
        self.verticalLayout_106 = QtWidgets.QVBoxLayout(self.group_param_modify_5)
        self.verticalLayout_106.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_106.setSpacing(0)
        self.verticalLayout_106.setObjectName("verticalLayout_106")
        self.frame_42 = QtWidgets.QFrame(self.group_param_modify_5)
        self.frame_42.setObjectName("frame_42")
        self.verticalLayout_107 = QtWidgets.QVBoxLayout(self.frame_42)
        self.verticalLayout_107.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_107.setSpacing(0)
        self.verticalLayout_107.setObjectName("verticalLayout_107")
        self.frame_43 = QtWidgets.QFrame(self.frame_42)
        self.frame_43.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_43.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_43.setObjectName("frame_43")
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout(self.frame_43)
        self.horizontalLayout_47.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_47.setSpacing(10)
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.verticalLayout_108 = QtWidgets.QVBoxLayout()
        self.verticalLayout_108.setSpacing(10)
        self.verticalLayout_108.setObjectName("verticalLayout_108")
        self.bt_forward_1 = QtWidgets.QPushButton(self.frame_43)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_forward_1.sizePolicy().hasHeightForWidth())
        self.bt_forward_1.setSizePolicy(sizePolicy)
        self.bt_forward_1.setObjectName("bt_forward_1")
        self.verticalLayout_108.addWidget(self.bt_forward_1)
        self.bt_reverse_1 = QtWidgets.QPushButton(self.frame_43)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_reverse_1.sizePolicy().hasHeightForWidth())
        self.bt_reverse_1.setSizePolicy(sizePolicy)
        self.bt_reverse_1.setObjectName("bt_reverse_1")
        self.verticalLayout_108.addWidget(self.bt_reverse_1)
        self.bt_halt_1 = QtWidgets.QPushButton(self.frame_43)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_halt_1.sizePolicy().hasHeightForWidth())
        self.bt_halt_1.setSizePolicy(sizePolicy)
        self.bt_halt_1.setObjectName("bt_halt_1")
        self.verticalLayout_108.addWidget(self.bt_halt_1)
        self.horizontalLayout_47.addLayout(self.verticalLayout_108)
        self.slider_1 = QtWidgets.QSlider(self.frame_43)
        self.slider_1.setMinimum(0)
        self.slider_1.setMaximum(100)
        self.slider_1.setSingleStep(1)
        self.slider_1.setPageStep(1)
        self.slider_1.setProperty("value", 0)
        self.slider_1.setOrientation(QtCore.Qt.Vertical)
        self.slider_1.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.slider_1.setObjectName("slider_1")
        self.horizontalLayout_47.addWidget(self.slider_1)
        self.frame_15 = QtWidgets.QFrame(self.frame_43)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.position_1 = QtWidgets.QLabel(self.frame_15)
        self.position_1.setAlignment(QtCore.Qt.AlignCenter)
        self.position_1.setIndent(-1)
        self.position_1.setObjectName("position_1")
        self.verticalLayout_11.addWidget(self.position_1)
        self.velocity_1 = QtWidgets.QLabel(self.frame_15)
        self.velocity_1.setAlignment(QtCore.Qt.AlignCenter)
        self.velocity_1.setIndent(-1)
        self.velocity_1.setObjectName("velocity_1")
        self.verticalLayout_11.addWidget(self.velocity_1)
        self.status_1 = QtWidgets.QLabel(self.frame_15)
        self.status_1.setAlignment(QtCore.Qt.AlignCenter)
        self.status_1.setIndent(-1)
        self.status_1.setObjectName("status_1")
        self.verticalLayout_11.addWidget(self.status_1)
        self.horizontalLayout_47.addWidget(self.frame_15)
        self.horizontalLayout_47.setStretch(0, 1)
        self.horizontalLayout_47.setStretch(1, 1)
        self.horizontalLayout_47.setStretch(2, 1)
        self.verticalLayout_107.addWidget(self.frame_43)
        self.verticalLayout_106.addWidget(self.frame_42)
        self.horizontalLayout_4.addWidget(self.group_param_modify_5)
        self.group_param_modify_7 = QtWidgets.QGroupBox(self.group_motor_control)
        self.group_param_modify_7.setEnabled(True)
        self.group_param_modify_7.setObjectName("group_param_modify_7")
        self.verticalLayout_113 = QtWidgets.QVBoxLayout(self.group_param_modify_7)
        self.verticalLayout_113.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_113.setSpacing(0)
        self.verticalLayout_113.setObjectName("verticalLayout_113")
        self.frame_46 = QtWidgets.QFrame(self.group_param_modify_7)
        self.frame_46.setObjectName("frame_46")
        self.verticalLayout_114 = QtWidgets.QVBoxLayout(self.frame_46)
        self.verticalLayout_114.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_114.setSpacing(0)
        self.verticalLayout_114.setObjectName("verticalLayout_114")
        self.frame_47 = QtWidgets.QFrame(self.frame_46)
        self.frame_47.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_47.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_47.setObjectName("frame_47")
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout(self.frame_47)
        self.horizontalLayout_49.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_49.setSpacing(7)
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.verticalLayout_115 = QtWidgets.QVBoxLayout()
        self.verticalLayout_115.setSpacing(10)
        self.verticalLayout_115.setObjectName("verticalLayout_115")
        self.bt_forward_2 = QtWidgets.QPushButton(self.frame_47)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_forward_2.sizePolicy().hasHeightForWidth())
        self.bt_forward_2.setSizePolicy(sizePolicy)
        self.bt_forward_2.setObjectName("bt_forward_2")
        self.verticalLayout_115.addWidget(self.bt_forward_2)
        self.bt_reverse_2 = QtWidgets.QPushButton(self.frame_47)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_reverse_2.sizePolicy().hasHeightForWidth())
        self.bt_reverse_2.setSizePolicy(sizePolicy)
        self.bt_reverse_2.setObjectName("bt_reverse_2")
        self.verticalLayout_115.addWidget(self.bt_reverse_2)
        self.bt_halt_2 = QtWidgets.QPushButton(self.frame_47)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_halt_2.sizePolicy().hasHeightForWidth())
        self.bt_halt_2.setSizePolicy(sizePolicy)
        self.bt_halt_2.setObjectName("bt_halt_2")
        self.verticalLayout_115.addWidget(self.bt_halt_2)
        self.horizontalLayout_49.addLayout(self.verticalLayout_115)
        self.slider_2 = QtWidgets.QSlider(self.frame_47)
        self.slider_2.setMinimum(0)
        self.slider_2.setMaximum(100)
        self.slider_2.setSingleStep(1)
        self.slider_2.setPageStep(1)
        self.slider_2.setProperty("value", 0)
        self.slider_2.setSliderPosition(0)
        self.slider_2.setOrientation(QtCore.Qt.Vertical)
        self.slider_2.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.slider_2.setObjectName("slider_2")
        self.horizontalLayout_49.addWidget(self.slider_2)
        self.frame_17 = QtWidgets.QFrame(self.frame_47)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.position_2 = QtWidgets.QLabel(self.frame_17)
        self.position_2.setAlignment(QtCore.Qt.AlignCenter)
        self.position_2.setIndent(-1)
        self.position_2.setObjectName("position_2")
        self.verticalLayout_14.addWidget(self.position_2)
        self.velocity_2 = QtWidgets.QLabel(self.frame_17)
        self.velocity_2.setAlignment(QtCore.Qt.AlignCenter)
        self.velocity_2.setIndent(-1)
        self.velocity_2.setObjectName("velocity_2")
        self.verticalLayout_14.addWidget(self.velocity_2)
        self.status_2 = QtWidgets.QLabel(self.frame_17)
        self.status_2.setAlignment(QtCore.Qt.AlignCenter)
        self.status_2.setIndent(-1)
        self.status_2.setObjectName("status_2")
        self.verticalLayout_14.addWidget(self.status_2)
        self.horizontalLayout_49.addWidget(self.frame_17)
        self.horizontalLayout_49.setStretch(0, 1)
        self.horizontalLayout_49.setStretch(1, 1)
        self.horizontalLayout_49.setStretch(2, 1)
        self.verticalLayout_114.addWidget(self.frame_47)
        self.verticalLayout_113.addWidget(self.frame_46)
        self.horizontalLayout_4.addWidget(self.group_param_modify_7)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 3)
        self.horizontalLayout_4.setStretch(2, 3)
        self.verticalLayout_7.addWidget(self.group_motor_control)
        self.verticalLayout_7.setStretch(0, 1)
        self.verticalLayout_7.setStretch(1, 3)
        self.verticalLayout_7.setStretch(2, 2)
        self.verticalLayout_7.setStretch(3, 3)
        self.stackedWidget.addWidget(self.pg_init)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.frame_2)
        self.verticalLayout.setStretch(0, 8)
        MainWindow.setCentralWidget(self.control_window)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "旋转进给控制面板"))
        self.group_init.setTitle(_translate("MainWindow", "【Initialization】"))
        self.bx_rate0.setItemText(0, _translate("MainWindow", "250K"))
        self.bx_rate1.setItemText(0, _translate("MainWindow", "1000K"))
        self.bt_open_device.setText(_translate("MainWindow", "Open Device"))
        self.bt_init_motor.setText(_translate("MainWindow", "Initialize Motor"))
        self.motor_check_1.setText(_translate("MainWindow", "Motor 1"))
        self.motor_check_2.setText(_translate("MainWindow", "Motor 2"))
        self.group_status_control.setTitle(_translate("MainWindow", "【Status Control】"))
        self.bt_shut_down.setText(_translate("MainWindow", "Shut Down"))
        self.bt_switch_on.setText(_translate("MainWindow", "Switch On"))
        self.bt_enable_operation.setText(_translate("MainWindow", "Enable Operation"))
        self.bt_disable_voltage.setText(_translate("MainWindow", "Disable Voltage"))
        self.bt_disable_operation.setText(_translate("MainWindow", "Disable Operation"))
        self.bt_quick_stop.setText(_translate("MainWindow", "Quick Stop"))
        self.bt_fault_reset.setText(_translate("MainWindow", "Fault Reset"))
        self.group_param.setTitle(_translate("MainWindow", "【Parameters】"))
        self.type_t.setText(_translate("MainWindow", "Trapezoidal"))
        self.type_s.setText(_translate("MainWindow", "Sinusoidal"))
        self.tx_acc.setText(_translate("MainWindow", "Acceleration"))
        self.le_acc.setPlaceholderText(_translate("MainWindow", "10000"))
        self.tx_dec.setText(_translate("MainWindow", "Deceleration"))
        self.le_dec.setPlaceholderText(_translate("MainWindow", "10000"))
        self.tx_quick.setText(_translate("MainWindow", "Quick Stop"))
        self.le_quick.setPlaceholderText(_translate("MainWindow", "100000"))
        self.tx_inhibit.setText(_translate("MainWindow", "Inhibit Time"))
        self.le_inhibit.setPlaceholderText(_translate("MainWindow", "10"))
        self.bt_save.setText(_translate("MainWindow", "Save"))
        self.bt_launch.setText(_translate("MainWindow", "Launch"))
        self.group_param_modify_6.setTitle(_translate("MainWindow", "【Mode】"))
        self.bt_lock.setText(_translate("MainWindow", "Lock"))
        self.bt_adaptive.setText(_translate("MainWindow", "Adaptive"))
        self.group_param_modify_5.setTitle(_translate("MainWindow", "【Motor 1】"))
        self.bt_forward_1.setText(_translate("MainWindow", "Forward"))
        self.bt_reverse_1.setText(_translate("MainWindow", "Reverse"))
        self.bt_halt_1.setText(_translate("MainWindow", "Halt"))
        self.position_1.setText(_translate("MainWindow", "Position"))
        self.velocity_1.setText(_translate("MainWindow", "Velocity"))
        self.status_1.setText(_translate("MainWindow", "Status"))
        self.group_param_modify_7.setTitle(_translate("MainWindow", "【Motor 2】"))
        self.bt_forward_2.setText(_translate("MainWindow", "Forward"))
        self.bt_reverse_2.setText(_translate("MainWindow", "Reverse"))
        self.bt_halt_2.setText(_translate("MainWindow", "Halt"))
        self.position_2.setText(_translate("MainWindow", "Position"))
        self.velocity_2.setText(_translate("MainWindow", "Velocity"))
        self.status_2.setText(_translate("MainWindow", "Status"))
