# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/control.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1048, 728)
        MainWindow.setStyleSheet("")
        self.control_window = QtWidgets.QWidget(MainWindow)
        self.control_window.setStyleSheet("QWidget {\n"
"    background-color: rgb(56, 57, 60);\n"
"}\n"
"\n"
"\n"
"QFrame {\n"
"    background-color: rgb(86, 88, 93);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"\n"
"QPushButton {\n"
"    background-color: rgb(114, 159, 207);\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:disabled {\n"
"    color: gray;\n"
"    background-color: rgb(86, 88, 93);\n"
"}\n"
"\n"
"QStackedWidget > QWidget {\n"
"    background-color: rgb(86, 88, 93);\n"
"    border-radius: 10px;\n"
"}\n"
"QStackedWidget QLabel {\n"
"    color: white;\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"}\n"
"QStackedWidget QLabel:disabled {\n"
"    color: gray;\n"
"}\n"
"\n"
"QStackedWidget QPushButton {\n"
"    background-color: rgb(114, 159, 207);\n"
"    font-size: 25px;\n"
"}\n"
"\n"
"QStackedWidget QRadioButton:disabled {\n"
"    font-size: 20px;\n"
"    color: gray;\n"
"    font-weight: bold;\n"
"    background-color: rgb(86, 88, 93);\n"
"}\n"
"QStackedWidget QRadioButton {\n"
"    font-size: 20px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    background-color: rgb(86, 88, 93);\n"
"}\n"
"\n"
"QStackedWidget QLineEdit {\n"
"    font-size: 20px;\n"
"    color: white;\n"
"    background-color: rgb(86, 88, 93);\n"
"}\n"
"\n"
"QStackedWidget QGroupBox {\n"
"    font-size: 20px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    background-color: rgb(86, 88, 93);\n"
"}\n"
"QStackedWidget QGroupBox:disabled {\n"
"    color: gray;\n"
"}\n"
"\n"
"QStackedWidget QComboBox {\n"
"    color: white;\n"
"    background-color: rgb(114, 159, 207);\n"
"    font-size: 25px;\n"
"    font-weight: bold;\n"
"    border-radius: 10px;\n"
"}\n"
"QStackedWidget QComboBox:disabled {\n"
"    background-color: rgb(86, 88, 93);\n"
"    color: gray;\n"
"}\n"
"\n"
"QStackedWidget QTextBrowser {\n"
"    color: white;\n"
"    font-size: 20px;\n"
"}")
        self.control_window.setObjectName("control_window")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.control_window)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.control_window)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bt_init = QtWidgets.QPushButton(self.frame)
        self.bt_init.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_init.sizePolicy().hasHeightForWidth())
        self.bt_init.setSizePolicy(sizePolicy)
        self.bt_init.setObjectName("bt_init")
        self.horizontalLayout.addWidget(self.bt_init)
        self.bt_control = QtWidgets.QPushButton(self.frame)
        self.bt_control.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_control.sizePolicy().hasHeightForWidth())
        self.bt_control.setSizePolicy(sizePolicy)
        self.bt_control.setObjectName("bt_control")
        self.horizontalLayout.addWidget(self.bt_control)
        self.bt_log = QtWidgets.QPushButton(self.frame)
        self.bt_log.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_log.sizePolicy().hasHeightForWidth())
        self.bt_log.setSizePolicy(sizePolicy)
        self.bt_log.setObjectName("bt_log")
        self.horizontalLayout.addWidget(self.bt_log)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.control_window)
        self.frame_2.setEnabled(True)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.pg_init = QtWidgets.QWidget()
        self.pg_init.setObjectName("pg_init")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.pg_init)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.group_usbcan = QtWidgets.QGroupBox(self.pg_init)
        self.group_usbcan.setObjectName("group_usbcan")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.group_usbcan)
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bt_open = QtWidgets.QPushButton(self.group_usbcan)
        self.bt_open.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_open.sizePolicy().hasHeightForWidth())
        self.bt_open.setSizePolicy(sizePolicy)
        self.bt_open.setObjectName("bt_open")
        self.horizontalLayout_2.addWidget(self.bt_open)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.bx_rate0 = QtWidgets.QComboBox(self.group_usbcan)
        self.bx_rate0.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bx_rate0.sizePolicy().hasHeightForWidth())
        self.bx_rate0.setSizePolicy(sizePolicy)
        self.bx_rate0.setObjectName("bx_rate0")
        self.bx_rate0.addItem("")
        self.bx_rate0.addItem("")
        self.verticalLayout_4.addWidget(self.bx_rate0)
        self.bx_rate1 = QtWidgets.QComboBox(self.group_usbcan)
        self.bx_rate1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bx_rate1.sizePolicy().hasHeightForWidth())
        self.bx_rate1.setSizePolicy(sizePolicy)
        self.bx_rate1.setObjectName("bx_rate1")
        self.bx_rate1.addItem("")
        self.bx_rate1.addItem("")
        self.verticalLayout_4.addWidget(self.bx_rate1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(15)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.bt_channel0 = QtWidgets.QPushButton(self.group_usbcan)
        self.bt_channel0.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_channel0.sizePolicy().hasHeightForWidth())
        self.bt_channel0.setSizePolicy(sizePolicy)
        self.bt_channel0.setObjectName("bt_channel0")
        self.verticalLayout_5.addWidget(self.bt_channel0)
        self.bt_channel1 = QtWidgets.QPushButton(self.group_usbcan)
        self.bt_channel1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_channel1.sizePolicy().hasHeightForWidth())
        self.bt_channel1.setSizePolicy(sizePolicy)
        self.bt_channel1.setObjectName("bt_channel1")
        self.verticalLayout_5.addWidget(self.bt_channel1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.bt_reset = QtWidgets.QPushButton(self.group_usbcan)
        self.bt_reset.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_reset.sizePolicy().hasHeightForWidth())
        self.bt_reset.setSizePolicy(sizePolicy)
        self.bt_reset.setObjectName("bt_reset")
        self.horizontalLayout_2.addWidget(self.bt_reset)
        self.bt_close = QtWidgets.QPushButton(self.group_usbcan)
        self.bt_close.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_close.sizePolicy().hasHeightForWidth())
        self.bt_close.setSizePolicy(sizePolicy)
        self.bt_close.setObjectName("bt_close")
        self.horizontalLayout_2.addWidget(self.bt_close)
        self.verticalLayout_7.addWidget(self.group_usbcan)
        self.group_motor = QtWidgets.QGroupBox(self.pg_init)
        self.group_motor.setEnabled(True)
        self.group_motor.setObjectName("group_motor")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.group_motor)
        self.horizontalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(15, -1, 15, -1)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.r_pos = QtWidgets.QRadioButton(self.group_motor)
        self.r_pos.setEnabled(True)
        self.r_pos.setCheckable(True)
        self.r_pos.setChecked(True)
        self.r_pos.setObjectName("r_pos")
        self.verticalLayout_6.addWidget(self.r_pos)
        self.r_vel = QtWidgets.QRadioButton(self.group_motor)
        self.r_vel.setEnabled(True)
        self.r_vel.setChecked(False)
        self.r_vel.setObjectName("r_vel")
        self.verticalLayout_6.addWidget(self.r_vel)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_8.setSpacing(10)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tx_acc = QtWidgets.QLabel(self.group_motor)
        self.tx_acc.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_acc.sizePolicy().hasHeightForWidth())
        self.tx_acc.setSizePolicy(sizePolicy)
        self.tx_acc.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_acc.setObjectName("tx_acc")
        self.verticalLayout_8.addWidget(self.tx_acc)
        self.le_acc = QtWidgets.QLineEdit(self.group_motor)
        self.le_acc.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_acc.sizePolicy().hasHeightForWidth())
        self.le_acc.setSizePolicy(sizePolicy)
        self.le_acc.setAlignment(QtCore.Qt.AlignCenter)
        self.le_acc.setObjectName("le_acc")
        self.verticalLayout_8.addWidget(self.le_acc)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_9.setSpacing(10)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tx_dec = QtWidgets.QLabel(self.group_motor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_dec.sizePolicy().hasHeightForWidth())
        self.tx_dec.setSizePolicy(sizePolicy)
        self.tx_dec.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_dec.setObjectName("tx_dec")
        self.verticalLayout_9.addWidget(self.tx_dec)
        self.le_dec = QtWidgets.QLineEdit(self.group_motor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_dec.sizePolicy().hasHeightForWidth())
        self.le_dec.setSizePolicy(sizePolicy)
        self.le_dec.setAlignment(QtCore.Qt.AlignCenter)
        self.le_dec.setObjectName("le_dec")
        self.verticalLayout_9.addWidget(self.le_dec)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_10.setSpacing(10)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.tx_vel = QtWidgets.QLabel(self.group_motor)
        self.tx_vel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_vel.sizePolicy().hasHeightForWidth())
        self.tx_vel.setSizePolicy(sizePolicy)
        self.tx_vel.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_vel.setObjectName("tx_vel")
        self.verticalLayout_10.addWidget(self.tx_vel)
        self.le_vel = QtWidgets.QLineEdit(self.group_motor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_vel.sizePolicy().hasHeightForWidth())
        self.le_vel.setSizePolicy(sizePolicy)
        self.le_vel.setAlignment(QtCore.Qt.AlignCenter)
        self.le_vel.setObjectName("le_vel")
        self.verticalLayout_10.addWidget(self.le_vel)
        self.horizontalLayout_3.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_11.setSpacing(10)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.tx_speed = QtWidgets.QLabel(self.group_motor)
        self.tx_speed.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_speed.sizePolicy().hasHeightForWidth())
        self.tx_speed.setSizePolicy(sizePolicy)
        self.tx_speed.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_speed.setObjectName("tx_speed")
        self.verticalLayout_11.addWidget(self.tx_speed)
        self.le_speed = QtWidgets.QLineEdit(self.group_motor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_speed.sizePolicy().hasHeightForWidth())
        self.le_speed.setSizePolicy(sizePolicy)
        self.le_speed.setAlignment(QtCore.Qt.AlignCenter)
        self.le_speed.setObjectName("le_speed")
        self.verticalLayout_11.addWidget(self.le_speed)
        self.horizontalLayout_3.addLayout(self.verticalLayout_11)
        self.bt_save = QtWidgets.QPushButton(self.group_motor)
        self.bt_save.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_save.sizePolicy().hasHeightForWidth())
        self.bt_save.setSizePolicy(sizePolicy)
        self.bt_save.setObjectName("bt_save")
        self.horizontalLayout_3.addWidget(self.bt_save)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 2)
        self.horizontalLayout_3.setStretch(2, 2)
        self.horizontalLayout_3.setStretch(3, 2)
        self.horizontalLayout_3.setStretch(4, 2)
        self.horizontalLayout_3.setStretch(5, 1)
        self.verticalLayout_7.addWidget(self.group_motor)
        self.groupBox_3 = QtWidgets.QGroupBox(self.pg_init)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_7.addWidget(self.groupBox_3)
        self.stackedWidget.addWidget(self.pg_init)
        self.pg_control = QtWidgets.QWidget()
        self.pg_control.setObjectName("pg_control")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.pg_control)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.groupBox = QtWidgets.QGroupBox(self.pg_control)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_4.setSpacing(7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSpacing(5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_12.addWidget(self.label)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_12.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_12.addWidget(self.pushButton_3)
        self.verticalLayout_12.setStretch(0, 1)
        self.verticalLayout_12.setStretch(1, 2)
        self.verticalLayout_12.setStretch(2, 2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_12)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setSpacing(5)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_14.addWidget(self.label_3)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_14.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_14.addWidget(self.pushButton_7)
        self.verticalLayout_14.setStretch(0, 1)
        self.verticalLayout_14.setStretch(1, 2)
        self.verticalLayout_14.setStretch(2, 2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setSpacing(5)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_15.addWidget(self.label_4)
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_15.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_15.addWidget(self.pushButton_9)
        self.verticalLayout_15.setStretch(0, 1)
        self.verticalLayout_15.setStretch(1, 2)
        self.verticalLayout_15.setStretch(2, 2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_15)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setSpacing(5)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_16.addWidget(self.label_5)
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_16.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_16.addWidget(self.pushButton_11)
        self.verticalLayout_16.setStretch(0, 1)
        self.verticalLayout_16.setStretch(1, 2)
        self.verticalLayout_16.setStretch(2, 2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_16)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setSpacing(5)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_17.addWidget(self.label_6)
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_17.addWidget(self.pushButton_12)
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_13.sizePolicy().hasHeightForWidth())
        self.pushButton_13.setSizePolicy(sizePolicy)
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_17.addWidget(self.pushButton_13)
        self.verticalLayout_17.setStretch(0, 1)
        self.verticalLayout_17.setStretch(1, 2)
        self.verticalLayout_17.setStretch(2, 2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_17)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setSpacing(5)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_18.addWidget(self.label_7)
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_14.sizePolicy().hasHeightForWidth())
        self.pushButton_14.setSizePolicy(sizePolicy)
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_18.addWidget(self.pushButton_14)
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_15.sizePolicy().hasHeightForWidth())
        self.pushButton_15.setSizePolicy(sizePolicy)
        self.pushButton_15.setObjectName("pushButton_15")
        self.verticalLayout_18.addWidget(self.pushButton_15)
        self.verticalLayout_18.setStretch(0, 1)
        self.verticalLayout_18.setStretch(1, 2)
        self.verticalLayout_18.setStretch(2, 2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_18)
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setSpacing(5)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_27.addWidget(self.label_15)
        self.pushButton_30 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_30.sizePolicy().hasHeightForWidth())
        self.pushButton_30.setSizePolicy(sizePolicy)
        self.pushButton_30.setObjectName("pushButton_30")
        self.verticalLayout_27.addWidget(self.pushButton_30)
        self.pushButton_31 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_31.sizePolicy().hasHeightForWidth())
        self.pushButton_31.setSizePolicy(sizePolicy)
        self.pushButton_31.setObjectName("pushButton_31")
        self.verticalLayout_27.addWidget(self.pushButton_31)
        self.verticalLayout_27.setStretch(0, 1)
        self.verticalLayout_27.setStretch(1, 2)
        self.verticalLayout_27.setStretch(2, 2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_27)
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setSpacing(5)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_28.addWidget(self.label_16)
        self.pushButton_32 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_32.sizePolicy().hasHeightForWidth())
        self.pushButton_32.setSizePolicy(sizePolicy)
        self.pushButton_32.setObjectName("pushButton_32")
        self.verticalLayout_28.addWidget(self.pushButton_32)
        self.pushButton_33 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_33.sizePolicy().hasHeightForWidth())
        self.pushButton_33.setSizePolicy(sizePolicy)
        self.pushButton_33.setObjectName("pushButton_33")
        self.verticalLayout_28.addWidget(self.pushButton_33)
        self.verticalLayout_28.setStretch(0, 1)
        self.verticalLayout_28.setStretch(1, 2)
        self.verticalLayout_28.setStretch(2, 2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_28)
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setSpacing(5)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_29.addWidget(self.label_17)
        self.pushButton_34 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_34.sizePolicy().hasHeightForWidth())
        self.pushButton_34.setSizePolicy(sizePolicy)
        self.pushButton_34.setObjectName("pushButton_34")
        self.verticalLayout_29.addWidget(self.pushButton_34)
        self.pushButton_35 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_35.sizePolicy().hasHeightForWidth())
        self.pushButton_35.setSizePolicy(sizePolicy)
        self.pushButton_35.setObjectName("pushButton_35")
        self.verticalLayout_29.addWidget(self.pushButton_35)
        self.verticalLayout_29.setStretch(0, 1)
        self.verticalLayout_29.setStretch(1, 2)
        self.verticalLayout_29.setStretch(2, 2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_29)
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setSpacing(5)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_30.addWidget(self.label_18)
        self.pushButton_36 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_36.sizePolicy().hasHeightForWidth())
        self.pushButton_36.setSizePolicy(sizePolicy)
        self.pushButton_36.setObjectName("pushButton_36")
        self.verticalLayout_30.addWidget(self.pushButton_36)
        self.pushButton_37 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_37.sizePolicy().hasHeightForWidth())
        self.pushButton_37.setSizePolicy(sizePolicy)
        self.pushButton_37.setObjectName("pushButton_37")
        self.verticalLayout_30.addWidget(self.pushButton_37)
        self.verticalLayout_30.setStretch(0, 1)
        self.verticalLayout_30.setStretch(1, 2)
        self.verticalLayout_30.setStretch(2, 2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_30)
        self.verticalLayout_22.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.pg_control)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_22.addWidget(self.groupBox_2)
        self.verticalLayout_22.setStretch(0, 1)
        self.verticalLayout_22.setStretch(1, 2)
        self.stackedWidget.addWidget(self.pg_control)
        self.pg_log = QtWidgets.QWidget()
        self.pg_log.setObjectName("pg_log")
        self.verticalLayout_49 = QtWidgets.QVBoxLayout(self.pg_log)
        self.verticalLayout_49.setObjectName("verticalLayout_49")
        self.groupBox_4 = QtWidgets.QGroupBox(self.pg_log)
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_28 = QtWidgets.QLabel(self.groupBox_4)
        self.label_28.setGeometry(QtCore.QRect(50, 50, 41, 41))
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_4)
        self.textBrowser.setGeometry(QtCore.QRect(30, 130, 91, 41))
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_49.addWidget(self.groupBox_4)
        self.groupBox_9 = QtWidgets.QGroupBox(self.pg_log)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_49.addWidget(self.groupBox_9)
        self.groupBox_10 = QtWidgets.QGroupBox(self.pg_log)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_49.addWidget(self.groupBox_10)
        self.stackedWidget.addWidget(self.pg_log)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.frame_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 8)
        MainWindow.setCentralWidget(self.control_window)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "龙骨式连续体机器人操作软件"))
        self.bt_init.setText(_translate("MainWindow", "初始化"))
        self.bt_control.setText(_translate("MainWindow", "操作面板"))
        self.bt_log.setText(_translate("MainWindow", "设备状态"))
        self.group_usbcan.setTitle(_translate("MainWindow", "配置CAN卡"))
        self.bt_open.setText(_translate("MainWindow", "打开设备"))
        self.bx_rate0.setItemText(0, _translate("MainWindow", "250K"))
        self.bx_rate0.setItemText(1, _translate("MainWindow", "500K"))
        self.bx_rate1.setItemText(0, _translate("MainWindow", "250K"))
        self.bx_rate1.setItemText(1, _translate("MainWindow", "500K"))
        self.bt_channel0.setText(_translate("MainWindow", "打开通道0"))
        self.bt_channel1.setText(_translate("MainWindow", "打开通道1"))
        self.bt_reset.setText(_translate("MainWindow", "重置CAN"))
        self.bt_close.setText(_translate("MainWindow", "关闭设备"))
        self.group_motor.setTitle(_translate("MainWindow", "配置电机"))
        self.r_pos.setText(_translate("MainWindow", "位置模式"))
        self.r_vel.setText(_translate("MainWindow", "速度模式"))
        self.tx_acc.setText(_translate("MainWindow", "加速度"))
        self.le_acc.setPlaceholderText(_translate("MainWindow", "默认值1000"))
        self.tx_dec.setText(_translate("MainWindow", "减速度"))
        self.le_dec.setPlaceholderText(_translate("MainWindow", "默认值10000"))
        self.tx_vel.setText(_translate("MainWindow", "动作速度"))
        self.le_vel.setPlaceholderText(_translate("MainWindow", "默认值100"))
        self.tx_speed.setText(_translate("MainWindow", "运行速度"))
        self.le_speed.setPlaceholderText(_translate("MainWindow", "默认值0"))
        self.bt_save.setText(_translate("MainWindow", "保存"))
        self.groupBox_3.setTitle(_translate("MainWindow", "配置"))
        self.groupBox.setTitle(_translate("MainWindow", "电机"))
        self.label.setText(_translate("MainWindow", "1"))
        self.pushButton_2.setText(_translate("MainWindow", "+"))
        self.pushButton_3.setText(_translate("MainWindow", "-"))
        self.label_3.setText(_translate("MainWindow", "2"))
        self.pushButton_6.setText(_translate("MainWindow", "+"))
        self.pushButton_7.setText(_translate("MainWindow", "-"))
        self.label_4.setText(_translate("MainWindow", "3"))
        self.pushButton_8.setText(_translate("MainWindow", "+"))
        self.pushButton_9.setText(_translate("MainWindow", "-"))
        self.label_5.setText(_translate("MainWindow", "4"))
        self.pushButton_10.setText(_translate("MainWindow", "+"))
        self.pushButton_11.setText(_translate("MainWindow", "-"))
        self.label_6.setText(_translate("MainWindow", "5"))
        self.pushButton_12.setText(_translate("MainWindow", "+"))
        self.pushButton_13.setText(_translate("MainWindow", "-"))
        self.label_7.setText(_translate("MainWindow", "6"))
        self.pushButton_14.setText(_translate("MainWindow", "+"))
        self.pushButton_15.setText(_translate("MainWindow", "-"))
        self.label_15.setText(_translate("MainWindow", "7"))
        self.pushButton_30.setText(_translate("MainWindow", "+"))
        self.pushButton_31.setText(_translate("MainWindow", "-"))
        self.label_16.setText(_translate("MainWindow", "8"))
        self.pushButton_32.setText(_translate("MainWindow", "+"))
        self.pushButton_33.setText(_translate("MainWindow", "-"))
        self.label_17.setText(_translate("MainWindow", "9"))
        self.pushButton_34.setText(_translate("MainWindow", "+"))
        self.pushButton_35.setText(_translate("MainWindow", "-"))
        self.label_18.setText(_translate("MainWindow", "10"))
        self.pushButton_36.setText(_translate("MainWindow", "+"))
        self.pushButton_37.setText(_translate("MainWindow", "-"))
        self.groupBox_2.setTitle(_translate("MainWindow", "末端"))
        self.groupBox_4.setTitle(_translate("MainWindow", "力传感器"))
        self.label_28.setText(_translate("MainWindow", "1"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:20px; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">0</span></p></body></html>"))
        self.groupBox_9.setTitle(_translate("MainWindow", "电机位置"))
        self.groupBox_10.setTitle(_translate("MainWindow", "其他"))
