# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/control_new.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 769)
        MainWindow.setStyleSheet("")
        self.control_window = QtWidgets.QWidget(MainWindow)
        self.control_window.setStyleSheet("QWidget {\n"
"    background-color: rgb(56, 57, 60);\n"
"}\n"
"\n"
"\n"
"QFrame {\n"
"    background-color: rgb(86, 88, 93);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"\n"
"QPushButton {\n"
"    background-color: rgb(114, 159, 207);\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:disabled {\n"
"    color: gray;\n"
"    background-color: rgb(86, 88, 93);\n"
"}\n"
"\n"
"QStackedWidget > QWidget {\n"
"    background-color: rgb(86, 88, 93);\n"
"    border-radius: 10px;\n"
"}\n"
"QStackedWidget QLabel {\n"
"    color: white;\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"}\n"
"QStackedWidget QLabel:disabled {\n"
"    color: gray;\n"
"}\n"
"\n"
"QStackedWidget QPushButton {\n"
"    background-color: rgb(114, 159, 207);\n"
"    font-size: 25px;\n"
"}\n"
"\n"
"QStackedWidget QRadioButton:disabled {\n"
"    font-size: 20px;\n"
"    color: gray;\n"
"    font-weight: bold;\n"
"    background-color: rgb(86, 88, 93);\n"
"}\n"
"QStackedWidget QRadioButton {\n"
"    font-size: 20px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    background-color: rgb(86, 88, 93);\n"
"}\n"
"\n"
"QStackedWidget QLineEdit {\n"
"    font-size: 20px;\n"
"    color: white;\n"
"    background-color: rgb(86, 88, 93);\n"
"}\n"
"\n"
"QStackedWidget QGroupBox {\n"
"    font-size: 20px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    background-color: rgb(86, 88, 93);\n"
"}\n"
"QStackedWidget QGroupBox:disabled {\n"
"    color: gray;\n"
"}\n"
"\n"
"QStackedWidget QComboBox {\n"
"    color: white;\n"
"    background-color: rgb(114, 159, 207);\n"
"    font-size: 25px;\n"
"    font-weight: bold;\n"
"    border-radius: 10px;\n"
"}\n"
"QStackedWidget QComboBox:disabled {\n"
"    background-color: rgb(86, 88, 93);\n"
"    color: gray;\n"
"}\n"
"\n"
"QStackedWidget QTextBrowser {\n"
"    color: white;\n"
"    font-size: 20px;\n"
"}")
        self.control_window.setObjectName("control_window")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.control_window)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.control_window)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bt_init = QtWidgets.QPushButton(self.frame)
        self.bt_init.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_init.sizePolicy().hasHeightForWidth())
        self.bt_init.setSizePolicy(sizePolicy)
        self.bt_init.setObjectName("bt_init")
        self.horizontalLayout.addWidget(self.bt_init)
        self.bt_control = QtWidgets.QPushButton(self.frame)
        self.bt_control.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_control.sizePolicy().hasHeightForWidth())
        self.bt_control.setSizePolicy(sizePolicy)
        self.bt_control.setObjectName("bt_control")
        self.horizontalLayout.addWidget(self.bt_control)
        self.bt_log = QtWidgets.QPushButton(self.frame)
        self.bt_log.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_log.sizePolicy().hasHeightForWidth())
        self.bt_log.setSizePolicy(sizePolicy)
        self.bt_log.setObjectName("bt_log")
        self.horizontalLayout.addWidget(self.bt_log)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.control_window)
        self.frame_2.setEnabled(True)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.pg_init = QtWidgets.QWidget()
        self.pg_init.setObjectName("pg_init")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.pg_init)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.group_usbcan = QtWidgets.QGroupBox(self.pg_init)
        self.group_usbcan.setObjectName("group_usbcan")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.group_usbcan)
        self.horizontalLayout_2.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bt_open = QtWidgets.QPushButton(self.group_usbcan)
        self.bt_open.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_open.sizePolicy().hasHeightForWidth())
        self.bt_open.setSizePolicy(sizePolicy)
        self.bt_open.setObjectName("bt_open")
        self.horizontalLayout_2.addWidget(self.bt_open)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.bx_rate0 = QtWidgets.QComboBox(self.group_usbcan)
        self.bx_rate0.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bx_rate0.sizePolicy().hasHeightForWidth())
        self.bx_rate0.setSizePolicy(sizePolicy)
        self.bx_rate0.setObjectName("bx_rate0")
        self.bx_rate0.addItem("")
        self.verticalLayout_4.addWidget(self.bx_rate0)
        self.bx_rate1 = QtWidgets.QComboBox(self.group_usbcan)
        self.bx_rate1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bx_rate1.sizePolicy().hasHeightForWidth())
        self.bx_rate1.setSizePolicy(sizePolicy)
        self.bx_rate1.setObjectName("bx_rate1")
        self.bx_rate1.addItem("")
        self.verticalLayout_4.addWidget(self.bx_rate1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(15)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.bt_channel0 = QtWidgets.QPushButton(self.group_usbcan)
        self.bt_channel0.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_channel0.sizePolicy().hasHeightForWidth())
        self.bt_channel0.setSizePolicy(sizePolicy)
        self.bt_channel0.setObjectName("bt_channel0")
        self.verticalLayout_5.addWidget(self.bt_channel0)
        self.bt_channel1 = QtWidgets.QPushButton(self.group_usbcan)
        self.bt_channel1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_channel1.sizePolicy().hasHeightForWidth())
        self.bt_channel1.setSizePolicy(sizePolicy)
        self.bt_channel1.setObjectName("bt_channel1")
        self.verticalLayout_5.addWidget(self.bt_channel1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_50 = QtWidgets.QVBoxLayout()
        self.verticalLayout_50.setSpacing(15)
        self.verticalLayout_50.setObjectName("verticalLayout_50")
        self.bt_reset0 = QtWidgets.QPushButton(self.group_usbcan)
        self.bt_reset0.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_reset0.sizePolicy().hasHeightForWidth())
        self.bt_reset0.setSizePolicy(sizePolicy)
        self.bt_reset0.setObjectName("bt_reset0")
        self.verticalLayout_50.addWidget(self.bt_reset0)
        self.bt_reset1 = QtWidgets.QPushButton(self.group_usbcan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_reset1.sizePolicy().hasHeightForWidth())
        self.bt_reset1.setSizePolicy(sizePolicy)
        self.bt_reset1.setObjectName("bt_reset1")
        self.verticalLayout_50.addWidget(self.bt_reset1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_50)
        self.bt_close = QtWidgets.QPushButton(self.group_usbcan)
        self.bt_close.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_close.sizePolicy().hasHeightForWidth())
        self.bt_close.setSizePolicy(sizePolicy)
        self.bt_close.setObjectName("bt_close")
        self.horizontalLayout_2.addWidget(self.bt_close)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 2)
        self.horizontalLayout_2.setStretch(3, 1)
        self.horizontalLayout_2.setStretch(4, 1)
        self.verticalLayout_7.addWidget(self.group_usbcan)
        self.group_motor = QtWidgets.QGroupBox(self.pg_init)
        self.group_motor.setEnabled(True)
        self.group_motor.setObjectName("group_motor")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.group_motor)
        self.verticalLayout_13.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_13.setSpacing(6)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_5 = QtWidgets.QFrame(self.group_motor)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.frame_8 = QtWidgets.QFrame(self.frame_5)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(10)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.check_all = QtWidgets.QPushButton(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_all.sizePolicy().hasHeightForWidth())
        self.check_all.setSizePolicy(sizePolicy)
        self.check_all.setMinimumSize(QtCore.QSize(0, 0))
        self.check_all.setObjectName("check_all")
        self.horizontalLayout_13.addWidget(self.check_all)
        self.horizontalLayout_13.setStretch(0, 3)
        self.verticalLayout_19.addWidget(self.frame_8)
        self.frame_4 = QtWidgets.QFrame(self.frame_5)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.check_1 = QtWidgets.QLabel(self.frame_4)
        self.check_1.setAlignment(QtCore.Qt.AlignCenter)
        self.check_1.setIndent(-1)
        self.check_1.setObjectName("check_1")
        self.horizontalLayout_3.addWidget(self.check_1)
        self.check_2 = QtWidgets.QLabel(self.frame_4)
        self.check_2.setAlignment(QtCore.Qt.AlignCenter)
        self.check_2.setIndent(-1)
        self.check_2.setObjectName("check_2")
        self.horizontalLayout_3.addWidget(self.check_2)
        self.check_3 = QtWidgets.QLabel(self.frame_4)
        self.check_3.setAlignment(QtCore.Qt.AlignCenter)
        self.check_3.setIndent(-1)
        self.check_3.setObjectName("check_3")
        self.horizontalLayout_3.addWidget(self.check_3)
        self.check_4 = QtWidgets.QLabel(self.frame_4)
        self.check_4.setAlignment(QtCore.Qt.AlignCenter)
        self.check_4.setIndent(-1)
        self.check_4.setObjectName("check_4")
        self.horizontalLayout_3.addWidget(self.check_4)
        self.check_5 = QtWidgets.QLabel(self.frame_4)
        self.check_5.setAlignment(QtCore.Qt.AlignCenter)
        self.check_5.setIndent(-1)
        self.check_5.setObjectName("check_5")
        self.horizontalLayout_3.addWidget(self.check_5)
        self.check_6 = QtWidgets.QLabel(self.frame_4)
        self.check_6.setAlignment(QtCore.Qt.AlignCenter)
        self.check_6.setIndent(-1)
        self.check_6.setObjectName("check_6")
        self.horizontalLayout_3.addWidget(self.check_6)
        self.check_7 = QtWidgets.QLabel(self.frame_4)
        self.check_7.setAlignment(QtCore.Qt.AlignCenter)
        self.check_7.setIndent(-1)
        self.check_7.setObjectName("check_7")
        self.horizontalLayout_3.addWidget(self.check_7)
        self.check_8 = QtWidgets.QLabel(self.frame_4)
        self.check_8.setAlignment(QtCore.Qt.AlignCenter)
        self.check_8.setIndent(-1)
        self.check_8.setObjectName("check_8")
        self.horizontalLayout_3.addWidget(self.check_8)
        self.check_9 = QtWidgets.QLabel(self.frame_4)
        self.check_9.setAlignment(QtCore.Qt.AlignCenter)
        self.check_9.setIndent(-1)
        self.check_9.setObjectName("check_9")
        self.horizontalLayout_3.addWidget(self.check_9)
        self.check_10 = QtWidgets.QLabel(self.frame_4)
        self.check_10.setAlignment(QtCore.Qt.AlignCenter)
        self.check_10.setIndent(-1)
        self.check_10.setObjectName("check_10")
        self.horizontalLayout_3.addWidget(self.check_10)
        self.check_11 = QtWidgets.QLabel(self.frame_4)
        self.check_11.setAlignment(QtCore.Qt.AlignCenter)
        self.check_11.setIndent(-1)
        self.check_11.setObjectName("check_11")
        self.horizontalLayout_3.addWidget(self.check_11)
        self.check_12 = QtWidgets.QLabel(self.frame_4)
        self.check_12.setAlignment(QtCore.Qt.AlignCenter)
        self.check_12.setIndent(-1)
        self.check_12.setObjectName("check_12")
        self.horizontalLayout_3.addWidget(self.check_12)
        self.check_13 = QtWidgets.QLabel(self.frame_4)
        self.check_13.setAlignment(QtCore.Qt.AlignCenter)
        self.check_13.setIndent(-1)
        self.check_13.setObjectName("check_13")
        self.horizontalLayout_3.addWidget(self.check_13)
        self.check_14 = QtWidgets.QLabel(self.frame_4)
        self.check_14.setAlignment(QtCore.Qt.AlignCenter)
        self.check_14.setIndent(-1)
        self.check_14.setObjectName("check_14")
        self.horizontalLayout_3.addWidget(self.check_14)
        self.verticalLayout_19.addWidget(self.frame_4)
        self.verticalLayout_13.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.group_motor)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(7)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.frame_3 = QtWidgets.QFrame(self.frame_6)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(7)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(15, -1, 15, -1)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.r_pos = QtWidgets.QRadioButton(self.frame_3)
        self.r_pos.setEnabled(True)
        self.r_pos.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.r_pos.setCheckable(True)
        self.r_pos.setChecked(True)
        self.r_pos.setObjectName("r_pos")
        self.verticalLayout_6.addWidget(self.r_pos)
        self.r_vel = QtWidgets.QRadioButton(self.frame_3)
        self.r_vel.setEnabled(True)
        self.r_vel.setChecked(False)
        self.r_vel.setObjectName("r_vel")
        self.verticalLayout_6.addWidget(self.r_vel)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_8.setSpacing(10)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tx_acc = QtWidgets.QLabel(self.frame_3)
        self.tx_acc.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_acc.sizePolicy().hasHeightForWidth())
        self.tx_acc.setSizePolicy(sizePolicy)
        self.tx_acc.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_acc.setObjectName("tx_acc")
        self.verticalLayout_8.addWidget(self.tx_acc)
        self.le_acc = QtWidgets.QLineEdit(self.frame_3)
        self.le_acc.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_acc.sizePolicy().hasHeightForWidth())
        self.le_acc.setSizePolicy(sizePolicy)
        self.le_acc.setAlignment(QtCore.Qt.AlignCenter)
        self.le_acc.setObjectName("le_acc")
        self.verticalLayout_8.addWidget(self.le_acc)
        self.horizontalLayout_5.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_9.setSpacing(10)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tx_dec = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_dec.sizePolicy().hasHeightForWidth())
        self.tx_dec.setSizePolicy(sizePolicy)
        self.tx_dec.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_dec.setObjectName("tx_dec")
        self.verticalLayout_9.addWidget(self.tx_dec)
        self.le_dec = QtWidgets.QLineEdit(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_dec.sizePolicy().hasHeightForWidth())
        self.le_dec.setSizePolicy(sizePolicy)
        self.le_dec.setAlignment(QtCore.Qt.AlignCenter)
        self.le_dec.setObjectName("le_dec")
        self.verticalLayout_9.addWidget(self.le_dec)
        self.horizontalLayout_5.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_10.setSpacing(10)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.tx_vel = QtWidgets.QLabel(self.frame_3)
        self.tx_vel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_vel.sizePolicy().hasHeightForWidth())
        self.tx_vel.setSizePolicy(sizePolicy)
        self.tx_vel.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_vel.setObjectName("tx_vel")
        self.verticalLayout_10.addWidget(self.tx_vel)
        self.le_vel = QtWidgets.QLineEdit(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_vel.sizePolicy().hasHeightForWidth())
        self.le_vel.setSizePolicy(sizePolicy)
        self.le_vel.setAlignment(QtCore.Qt.AlignCenter)
        self.le_vel.setObjectName("le_vel")
        self.verticalLayout_10.addWidget(self.le_vel)
        self.horizontalLayout_5.addLayout(self.verticalLayout_10)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_21.setSpacing(10)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.tx_position = QtWidgets.QLabel(self.frame_3)
        self.tx_position.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_position.sizePolicy().hasHeightForWidth())
        self.tx_position.setSizePolicy(sizePolicy)
        self.tx_position.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_position.setObjectName("tx_position")
        self.verticalLayout_21.addWidget(self.tx_position)
        self.le_position = QtWidgets.QLineEdit(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_position.sizePolicy().hasHeightForWidth())
        self.le_position.setSizePolicy(sizePolicy)
        self.le_position.setAlignment(QtCore.Qt.AlignCenter)
        self.le_position.setObjectName("le_position")
        self.verticalLayout_21.addWidget(self.le_position)
        self.horizontalLayout_5.addLayout(self.verticalLayout_21)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_11.setSpacing(10)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.tx_inhibit = QtWidgets.QLabel(self.frame_3)
        self.tx_inhibit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_inhibit.sizePolicy().hasHeightForWidth())
        self.tx_inhibit.setSizePolicy(sizePolicy)
        self.tx_inhibit.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_inhibit.setObjectName("tx_inhibit")
        self.verticalLayout_11.addWidget(self.tx_inhibit)
        self.le_inhibit = QtWidgets.QLineEdit(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_inhibit.sizePolicy().hasHeightForWidth())
        self.le_inhibit.setSizePolicy(sizePolicy)
        self.le_inhibit.setAlignment(QtCore.Qt.AlignCenter)
        self.le_inhibit.setObjectName("le_inhibit")
        self.verticalLayout_11.addWidget(self.le_inhibit)
        self.horizontalLayout_5.addLayout(self.verticalLayout_11)
        self.verticalLayout_51 = QtWidgets.QVBoxLayout()
        self.verticalLayout_51.setSpacing(10)
        self.verticalLayout_51.setObjectName("verticalLayout_51")
        self.bt_save = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_save.sizePolicy().hasHeightForWidth())
        self.bt_save.setSizePolicy(sizePolicy)
        self.bt_save.setObjectName("bt_save")
        self.verticalLayout_51.addWidget(self.bt_save)
        self.bt_launch = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_launch.sizePolicy().hasHeightForWidth())
        self.bt_launch.setSizePolicy(sizePolicy)
        self.bt_launch.setObjectName("bt_launch")
        self.verticalLayout_51.addWidget(self.bt_launch)
        self.horizontalLayout_5.addLayout(self.verticalLayout_51)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 2)
        self.horizontalLayout_5.setStretch(2, 2)
        self.horizontalLayout_5.setStretch(3, 2)
        self.horizontalLayout_5.setStretch(4, 2)
        self.horizontalLayout_5.setStretch(5, 2)
        self.horizontalLayout_5.setStretch(6, 2)
        self.verticalLayout_20.addWidget(self.frame_3)
        self.verticalLayout_13.addWidget(self.frame_6)
        self.frame_9 = QtWidgets.QFrame(self.group_motor)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_6.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.frame_9)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(10)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.start = QtWidgets.QPushButton(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start.sizePolicy().hasHeightForWidth())
        self.start.setSizePolicy(sizePolicy)
        self.start.setObjectName("start")
        self.verticalLayout_12.addWidget(self.start)
        self.stop = QtWidgets.QPushButton(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop.sizePolicy().hasHeightForWidth())
        self.stop.setSizePolicy(sizePolicy)
        self.stop.setObjectName("stop")
        self.verticalLayout_12.addWidget(self.stop)
        self.horizontalLayout_6.addWidget(self.frame_11)
        self.horizontalLayout_6.setStretch(0, 2)
        self.horizontalLayout_6.setStretch(1, 1)
        self.verticalLayout_13.addWidget(self.frame_9)
        self.verticalLayout_7.addWidget(self.group_motor)
        self.verticalLayout_7.setStretch(0, 1)
        self.verticalLayout_7.setStretch(1, 5)
        self.stackedWidget.addWidget(self.pg_init)
        self.pg_control = QtWidgets.QWidget()
        self.pg_control.setObjectName("pg_control")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.pg_control)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.group_status = QtWidgets.QGroupBox(self.pg_control)
        self.group_status.setObjectName("group_status")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.group_status)
        self.horizontalLayout_9.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_9.setSpacing(10)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.bt_quick_stop = QtWidgets.QPushButton(self.group_status)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_quick_stop.sizePolicy().hasHeightForWidth())
        self.bt_quick_stop.setSizePolicy(sizePolicy)
        self.bt_quick_stop.setObjectName("bt_quick_stop")
        self.horizontalLayout_9.addWidget(self.bt_quick_stop)
        self.bt_unlock = QtWidgets.QPushButton(self.group_status)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_unlock.sizePolicy().hasHeightForWidth())
        self.bt_unlock.setSizePolicy(sizePolicy)
        self.bt_unlock.setObjectName("bt_unlock")
        self.horizontalLayout_9.addWidget(self.bt_unlock)
        self.bt_enable = QtWidgets.QPushButton(self.group_status)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_enable.sizePolicy().hasHeightForWidth())
        self.bt_enable.setSizePolicy(sizePolicy)
        self.bt_enable.setObjectName("bt_enable")
        self.horizontalLayout_9.addWidget(self.bt_enable)
        self.horizontalLayout_9.setStretch(0, 1)
        self.horizontalLayout_9.setStretch(1, 1)
        self.horizontalLayout_9.setStretch(2, 1)
        self.verticalLayout_22.addWidget(self.group_status)
        self.group_control = QtWidgets.QGroupBox(self.pg_control)
        self.group_control.setObjectName("group_control")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.group_control)
        self.verticalLayout_31.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_31.setSpacing(0)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setSpacing(15)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.bt_joint_control = QtWidgets.QPushButton(self.group_control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_joint_control.sizePolicy().hasHeightForWidth())
        self.bt_joint_control.setSizePolicy(sizePolicy)
        self.bt_joint_control.setObjectName("bt_joint_control")
        self.horizontalLayout_29.addWidget(self.bt_joint_control)
        self.bt_quit = QtWidgets.QPushButton(self.group_control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_quit.sizePolicy().hasHeightForWidth())
        self.bt_quit.setSizePolicy(sizePolicy)
        self.bt_quit.setObjectName("bt_quit")
        self.horizontalLayout_29.addWidget(self.bt_quit)
        self.verticalLayout_31.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(15)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.group_1 = QtWidgets.QGroupBox(self.group_control)
        self.group_1.setAlignment(QtCore.Qt.AlignCenter)
        self.group_1.setObjectName("group_1")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.group_1)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(10)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.bt_negative_1 = QtWidgets.QPushButton(self.group_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_negative_1.sizePolicy().hasHeightForWidth())
        self.bt_negative_1.setSizePolicy(sizePolicy)
        self.bt_negative_1.setObjectName("bt_negative_1")
        self.horizontalLayout_11.addWidget(self.bt_negative_1)
        self.bt_positive_1 = QtWidgets.QPushButton(self.group_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_positive_1.sizePolicy().hasHeightForWidth())
        self.bt_positive_1.setSizePolicy(sizePolicy)
        self.bt_positive_1.setObjectName("bt_positive_1")
        self.horizontalLayout_11.addWidget(self.bt_positive_1)
        self.horizontalLayout_4.addWidget(self.group_1)
        self.group_2 = QtWidgets.QGroupBox(self.group_control)
        self.group_2.setAlignment(QtCore.Qt.AlignCenter)
        self.group_2.setObjectName("group_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.group_2)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(10)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.bt_negative_2 = QtWidgets.QPushButton(self.group_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_negative_2.sizePolicy().hasHeightForWidth())
        self.bt_negative_2.setSizePolicy(sizePolicy)
        self.bt_negative_2.setObjectName("bt_negative_2")
        self.horizontalLayout_12.addWidget(self.bt_negative_2)
        self.bt_positive_2 = QtWidgets.QPushButton(self.group_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_positive_2.sizePolicy().hasHeightForWidth())
        self.bt_positive_2.setSizePolicy(sizePolicy)
        self.bt_positive_2.setObjectName("bt_positive_2")
        self.horizontalLayout_12.addWidget(self.bt_positive_2)
        self.horizontalLayout_4.addWidget(self.group_2)
        self.group_3 = QtWidgets.QGroupBox(self.group_control)
        self.group_3.setAlignment(QtCore.Qt.AlignCenter)
        self.group_3.setObjectName("group_3")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.group_3)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(10)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.bt_negative_3 = QtWidgets.QPushButton(self.group_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_negative_3.sizePolicy().hasHeightForWidth())
        self.bt_negative_3.setSizePolicy(sizePolicy)
        self.bt_negative_3.setObjectName("bt_negative_3")
        self.horizontalLayout_14.addWidget(self.bt_negative_3)
        self.bt_positive_3 = QtWidgets.QPushButton(self.group_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_positive_3.sizePolicy().hasHeightForWidth())
        self.bt_positive_3.setSizePolicy(sizePolicy)
        self.bt_positive_3.setObjectName("bt_positive_3")
        self.horizontalLayout_14.addWidget(self.bt_positive_3)
        self.horizontalLayout_4.addWidget(self.group_3)
        self.group_4 = QtWidgets.QGroupBox(self.group_control)
        self.group_4.setAlignment(QtCore.Qt.AlignCenter)
        self.group_4.setObjectName("group_4")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.group_4)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(10)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.bt_negative_4 = QtWidgets.QPushButton(self.group_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_negative_4.sizePolicy().hasHeightForWidth())
        self.bt_negative_4.setSizePolicy(sizePolicy)
        self.bt_negative_4.setObjectName("bt_negative_4")
        self.horizontalLayout_15.addWidget(self.bt_negative_4)
        self.bt_positive_4 = QtWidgets.QPushButton(self.group_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_positive_4.sizePolicy().hasHeightForWidth())
        self.bt_positive_4.setSizePolicy(sizePolicy)
        self.bt_positive_4.setObjectName("bt_positive_4")
        self.horizontalLayout_15.addWidget(self.bt_positive_4)
        self.horizontalLayout_4.addWidget(self.group_4)
        self.group_5 = QtWidgets.QGroupBox(self.group_control)
        self.group_5.setAlignment(QtCore.Qt.AlignCenter)
        self.group_5.setObjectName("group_5")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.group_5)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(10)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.bt_negative_5 = QtWidgets.QPushButton(self.group_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_negative_5.sizePolicy().hasHeightForWidth())
        self.bt_negative_5.setSizePolicy(sizePolicy)
        self.bt_negative_5.setObjectName("bt_negative_5")
        self.horizontalLayout_16.addWidget(self.bt_negative_5)
        self.bt_positive_5 = QtWidgets.QPushButton(self.group_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_positive_5.sizePolicy().hasHeightForWidth())
        self.bt_positive_5.setSizePolicy(sizePolicy)
        self.bt_positive_5.setObjectName("bt_positive_5")
        self.horizontalLayout_16.addWidget(self.bt_positive_5)
        self.horizontalLayout_4.addWidget(self.group_5)
        self.group_6 = QtWidgets.QGroupBox(self.group_control)
        self.group_6.setAlignment(QtCore.Qt.AlignCenter)
        self.group_6.setObjectName("group_6")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.group_6)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(10)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.bt_negative_6 = QtWidgets.QPushButton(self.group_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_negative_6.sizePolicy().hasHeightForWidth())
        self.bt_negative_6.setSizePolicy(sizePolicy)
        self.bt_negative_6.setObjectName("bt_negative_6")
        self.horizontalLayout_17.addWidget(self.bt_negative_6)
        self.bt_positive_6 = QtWidgets.QPushButton(self.group_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_positive_6.sizePolicy().hasHeightForWidth())
        self.bt_positive_6.setSizePolicy(sizePolicy)
        self.bt_positive_6.setObjectName("bt_positive_6")
        self.horizontalLayout_17.addWidget(self.bt_positive_6)
        self.horizontalLayout_4.addWidget(self.group_6)
        self.verticalLayout_31.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(15)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.group_7 = QtWidgets.QGroupBox(self.group_control)
        self.group_7.setAlignment(QtCore.Qt.AlignCenter)
        self.group_7.setObjectName("group_7")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.group_7)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(10)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.bt_negative_7 = QtWidgets.QPushButton(self.group_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_negative_7.sizePolicy().hasHeightForWidth())
        self.bt_negative_7.setSizePolicy(sizePolicy)
        self.bt_negative_7.setObjectName("bt_negative_7")
        self.horizontalLayout_18.addWidget(self.bt_negative_7)
        self.bt_positive_7 = QtWidgets.QPushButton(self.group_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_positive_7.sizePolicy().hasHeightForWidth())
        self.bt_positive_7.setSizePolicy(sizePolicy)
        self.bt_positive_7.setObjectName("bt_positive_7")
        self.horizontalLayout_18.addWidget(self.bt_positive_7)
        self.horizontalLayout_7.addWidget(self.group_7)
        self.group_8 = QtWidgets.QGroupBox(self.group_control)
        self.group_8.setAlignment(QtCore.Qt.AlignCenter)
        self.group_8.setObjectName("group_8")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.group_8)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(10)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.bt_negative_8 = QtWidgets.QPushButton(self.group_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_negative_8.sizePolicy().hasHeightForWidth())
        self.bt_negative_8.setSizePolicy(sizePolicy)
        self.bt_negative_8.setObjectName("bt_negative_8")
        self.horizontalLayout_19.addWidget(self.bt_negative_8)
        self.bt_positive_8 = QtWidgets.QPushButton(self.group_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_positive_8.sizePolicy().hasHeightForWidth())
        self.bt_positive_8.setSizePolicy(sizePolicy)
        self.bt_positive_8.setObjectName("bt_positive_8")
        self.horizontalLayout_19.addWidget(self.bt_positive_8)
        self.horizontalLayout_7.addWidget(self.group_8)
        self.group_9 = QtWidgets.QGroupBox(self.group_control)
        self.group_9.setAlignment(QtCore.Qt.AlignCenter)
        self.group_9.setObjectName("group_9")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.group_9)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setSpacing(10)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.bt_negative_9 = QtWidgets.QPushButton(self.group_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_negative_9.sizePolicy().hasHeightForWidth())
        self.bt_negative_9.setSizePolicy(sizePolicy)
        self.bt_negative_9.setObjectName("bt_negative_9")
        self.horizontalLayout_20.addWidget(self.bt_negative_9)
        self.bt_positive_9 = QtWidgets.QPushButton(self.group_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_positive_9.sizePolicy().hasHeightForWidth())
        self.bt_positive_9.setSizePolicy(sizePolicy)
        self.bt_positive_9.setObjectName("bt_positive_9")
        self.horizontalLayout_20.addWidget(self.bt_positive_9)
        self.horizontalLayout_7.addWidget(self.group_9)
        self.group_10 = QtWidgets.QGroupBox(self.group_control)
        self.group_10.setAlignment(QtCore.Qt.AlignCenter)
        self.group_10.setObjectName("group_10")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.group_10)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setSpacing(10)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.bt_negative_10 = QtWidgets.QPushButton(self.group_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_negative_10.sizePolicy().hasHeightForWidth())
        self.bt_negative_10.setSizePolicy(sizePolicy)
        self.bt_negative_10.setObjectName("bt_negative_10")
        self.horizontalLayout_21.addWidget(self.bt_negative_10)
        self.bt_positive_10 = QtWidgets.QPushButton(self.group_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_positive_10.sizePolicy().hasHeightForWidth())
        self.bt_positive_10.setSizePolicy(sizePolicy)
        self.bt_positive_10.setObjectName("bt_positive_10")
        self.horizontalLayout_21.addWidget(self.bt_positive_10)
        self.horizontalLayout_7.addWidget(self.group_10)
        self.group_11 = QtWidgets.QGroupBox(self.group_control)
        self.group_11.setAlignment(QtCore.Qt.AlignCenter)
        self.group_11.setObjectName("group_11")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.group_11)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setSpacing(10)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.bt_negative_11 = QtWidgets.QPushButton(self.group_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_negative_11.sizePolicy().hasHeightForWidth())
        self.bt_negative_11.setSizePolicy(sizePolicy)
        self.bt_negative_11.setObjectName("bt_negative_11")
        self.horizontalLayout_22.addWidget(self.bt_negative_11)
        self.bt_positive_11 = QtWidgets.QPushButton(self.group_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_positive_11.sizePolicy().hasHeightForWidth())
        self.bt_positive_11.setSizePolicy(sizePolicy)
        self.bt_positive_11.setObjectName("bt_positive_11")
        self.horizontalLayout_22.addWidget(self.bt_positive_11)
        self.horizontalLayout_7.addWidget(self.group_11)
        self.group_12 = QtWidgets.QGroupBox(self.group_control)
        self.group_12.setAlignment(QtCore.Qt.AlignCenter)
        self.group_12.setObjectName("group_12")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.group_12)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setSpacing(10)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.bt_negative_12 = QtWidgets.QPushButton(self.group_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_negative_12.sizePolicy().hasHeightForWidth())
        self.bt_negative_12.setSizePolicy(sizePolicy)
        self.bt_negative_12.setObjectName("bt_negative_12")
        self.horizontalLayout_23.addWidget(self.bt_negative_12)
        self.bt_positive_12 = QtWidgets.QPushButton(self.group_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_positive_12.sizePolicy().hasHeightForWidth())
        self.bt_positive_12.setSizePolicy(sizePolicy)
        self.bt_positive_12.setObjectName("bt_positive_12")
        self.horizontalLayout_23.addWidget(self.bt_positive_12)
        self.horizontalLayout_7.addWidget(self.group_12)
        self.verticalLayout_31.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(15)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.group_13 = QtWidgets.QGroupBox(self.group_control)
        self.group_13.setAlignment(QtCore.Qt.AlignCenter)
        self.group_13.setObjectName("group_13")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.group_13)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setSpacing(10)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.bt_negative_13 = QtWidgets.QPushButton(self.group_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_negative_13.sizePolicy().hasHeightForWidth())
        self.bt_negative_13.setSizePolicy(sizePolicy)
        self.bt_negative_13.setObjectName("bt_negative_13")
        self.horizontalLayout_24.addWidget(self.bt_negative_13)
        self.bt_positive_13 = QtWidgets.QPushButton(self.group_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_positive_13.sizePolicy().hasHeightForWidth())
        self.bt_positive_13.setSizePolicy(sizePolicy)
        self.bt_positive_13.setObjectName("bt_positive_13")
        self.horizontalLayout_24.addWidget(self.bt_positive_13)
        self.horizontalLayout_8.addWidget(self.group_13)
        self.group_14 = QtWidgets.QGroupBox(self.group_control)
        self.group_14.setAlignment(QtCore.Qt.AlignCenter)
        self.group_14.setObjectName("group_14")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.group_14)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setSpacing(10)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.bt_negative_14 = QtWidgets.QPushButton(self.group_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_negative_14.sizePolicy().hasHeightForWidth())
        self.bt_negative_14.setSizePolicy(sizePolicy)
        self.bt_negative_14.setObjectName("bt_negative_14")
        self.horizontalLayout_25.addWidget(self.bt_negative_14)
        self.bt_positive_14 = QtWidgets.QPushButton(self.group_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_positive_14.sizePolicy().hasHeightForWidth())
        self.bt_positive_14.setSizePolicy(sizePolicy)
        self.bt_positive_14.setObjectName("bt_positive_14")
        self.horizontalLayout_25.addWidget(self.bt_positive_14)
        self.horizontalLayout_8.addWidget(self.group_14)
        self.verticalLayout_31.addLayout(self.horizontalLayout_8)
        self.verticalLayout_22.addWidget(self.group_control)
        self.frame_7 = QtWidgets.QFrame(self.pg_control)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_10.setContentsMargins(5, 10, 5, 0)
        self.horizontalLayout_10.setSpacing(15)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.bt_end_control = QtWidgets.QPushButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_end_control.sizePolicy().hasHeightForWidth())
        self.bt_end_control.setSizePolicy(sizePolicy)
        self.bt_end_control.setObjectName("bt_end_control")
        self.horizontalLayout_10.addWidget(self.bt_end_control)
        self.bt_exit = QtWidgets.QPushButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_exit.sizePolicy().hasHeightForWidth())
        self.bt_exit.setSizePolicy(sizePolicy)
        self.bt_exit.setObjectName("bt_exit")
        self.horizontalLayout_10.addWidget(self.bt_exit)
        self.verticalLayout_22.addWidget(self.frame_7)
        self.verticalLayout_22.setStretch(0, 3)
        self.verticalLayout_22.setStretch(1, 10)
        self.verticalLayout_22.setStretch(2, 2)
        self.stackedWidget.addWidget(self.pg_control)
        self.pg_log = QtWidgets.QWidget()
        self.pg_log.setObjectName("pg_log")
        self.verticalLayout_49 = QtWidgets.QVBoxLayout(self.pg_log)
        self.verticalLayout_49.setContentsMargins(0, 0, 10, 0)
        self.verticalLayout_49.setObjectName("verticalLayout_49")
        self.frame1 = QtWidgets.QFrame(self.pg_log)
        self.frame1.setObjectName("frame1")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.frame1)
        self.verticalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_33.setSpacing(0)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setSpacing(0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.status_1 = QtWidgets.QGroupBox(self.frame1)
        self.status_1.setAlignment(QtCore.Qt.AlignCenter)
        self.status_1.setObjectName("status_1")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.status_1)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.servo_1 = QtWidgets.QLabel(self.status_1)
        self.servo_1.setAlignment(QtCore.Qt.AlignCenter)
        self.servo_1.setObjectName("servo_1")
        self.verticalLayout_14.addWidget(self.servo_1)
        self.position_1 = QtWidgets.QLabel(self.status_1)
        self.position_1.setAlignment(QtCore.Qt.AlignCenter)
        self.position_1.setObjectName("position_1")
        self.verticalLayout_14.addWidget(self.position_1)
        self.speed_1 = QtWidgets.QLabel(self.status_1)
        self.speed_1.setAlignment(QtCore.Qt.AlignCenter)
        self.speed_1.setObjectName("speed_1")
        self.verticalLayout_14.addWidget(self.speed_1)
        self.horizontalLayout_26.addWidget(self.status_1)
        self.status_2 = QtWidgets.QGroupBox(self.frame1)
        self.status_2.setAlignment(QtCore.Qt.AlignCenter)
        self.status_2.setObjectName("status_2")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.status_2)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.servo_2 = QtWidgets.QLabel(self.status_2)
        self.servo_2.setAlignment(QtCore.Qt.AlignCenter)
        self.servo_2.setObjectName("servo_2")
        self.verticalLayout_15.addWidget(self.servo_2)
        self.position_2 = QtWidgets.QLabel(self.status_2)
        self.position_2.setAlignment(QtCore.Qt.AlignCenter)
        self.position_2.setObjectName("position_2")
        self.verticalLayout_15.addWidget(self.position_2)
        self.speed_2 = QtWidgets.QLabel(self.status_2)
        self.speed_2.setAlignment(QtCore.Qt.AlignCenter)
        self.speed_2.setObjectName("speed_2")
        self.verticalLayout_15.addWidget(self.speed_2)
        self.horizontalLayout_26.addWidget(self.status_2)
        self.status_3 = QtWidgets.QGroupBox(self.frame1)
        self.status_3.setAlignment(QtCore.Qt.AlignCenter)
        self.status_3.setObjectName("status_3")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.status_3)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.servo_3 = QtWidgets.QLabel(self.status_3)
        self.servo_3.setAlignment(QtCore.Qt.AlignCenter)
        self.servo_3.setObjectName("servo_3")
        self.verticalLayout_16.addWidget(self.servo_3)
        self.position_3 = QtWidgets.QLabel(self.status_3)
        self.position_3.setAlignment(QtCore.Qt.AlignCenter)
        self.position_3.setObjectName("position_3")
        self.verticalLayout_16.addWidget(self.position_3)
        self.speed_3 = QtWidgets.QLabel(self.status_3)
        self.speed_3.setAlignment(QtCore.Qt.AlignCenter)
        self.speed_3.setObjectName("speed_3")
        self.verticalLayout_16.addWidget(self.speed_3)
        self.horizontalLayout_26.addWidget(self.status_3)
        self.status_4 = QtWidgets.QGroupBox(self.frame1)
        self.status_4.setAlignment(QtCore.Qt.AlignCenter)
        self.status_4.setObjectName("status_4")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.status_4)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.servo_4 = QtWidgets.QLabel(self.status_4)
        self.servo_4.setAlignment(QtCore.Qt.AlignCenter)
        self.servo_4.setObjectName("servo_4")
        self.verticalLayout_17.addWidget(self.servo_4)
        self.position_4 = QtWidgets.QLabel(self.status_4)
        self.position_4.setAlignment(QtCore.Qt.AlignCenter)
        self.position_4.setObjectName("position_4")
        self.verticalLayout_17.addWidget(self.position_4)
        self.speed_4 = QtWidgets.QLabel(self.status_4)
        self.speed_4.setAlignment(QtCore.Qt.AlignCenter)
        self.speed_4.setObjectName("speed_4")
        self.verticalLayout_17.addWidget(self.speed_4)
        self.horizontalLayout_26.addWidget(self.status_4)
        self.status_5 = QtWidgets.QGroupBox(self.frame1)
        self.status_5.setAlignment(QtCore.Qt.AlignCenter)
        self.status_5.setObjectName("status_5")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.status_5)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.servo_5 = QtWidgets.QLabel(self.status_5)
        self.servo_5.setAlignment(QtCore.Qt.AlignCenter)
        self.servo_5.setObjectName("servo_5")
        self.verticalLayout_18.addWidget(self.servo_5)
        self.position_5 = QtWidgets.QLabel(self.status_5)
        self.position_5.setAlignment(QtCore.Qt.AlignCenter)
        self.position_5.setObjectName("position_5")
        self.verticalLayout_18.addWidget(self.position_5)
        self.speed_5 = QtWidgets.QLabel(self.status_5)
        self.speed_5.setAlignment(QtCore.Qt.AlignCenter)
        self.speed_5.setObjectName("speed_5")
        self.verticalLayout_18.addWidget(self.speed_5)
        self.horizontalLayout_26.addWidget(self.status_5)
        self.verticalLayout_33.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setSpacing(0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.status_6 = QtWidgets.QGroupBox(self.frame1)
        self.status_6.setAlignment(QtCore.Qt.AlignCenter)
        self.status_6.setObjectName("status_6")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.status_6)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setSpacing(0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.servo_6 = QtWidgets.QLabel(self.status_6)
        self.servo_6.setAlignment(QtCore.Qt.AlignCenter)
        self.servo_6.setObjectName("servo_6")
        self.verticalLayout_23.addWidget(self.servo_6)
        self.position_6 = QtWidgets.QLabel(self.status_6)
        self.position_6.setAlignment(QtCore.Qt.AlignCenter)
        self.position_6.setObjectName("position_6")
        self.verticalLayout_23.addWidget(self.position_6)
        self.speed_6 = QtWidgets.QLabel(self.status_6)
        self.speed_6.setAlignment(QtCore.Qt.AlignCenter)
        self.speed_6.setObjectName("speed_6")
        self.verticalLayout_23.addWidget(self.speed_6)
        self.horizontalLayout_27.addWidget(self.status_6)
        self.status_7 = QtWidgets.QGroupBox(self.frame1)
        self.status_7.setAlignment(QtCore.Qt.AlignCenter)
        self.status_7.setObjectName("status_7")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.status_7)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setSpacing(0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.servo_7 = QtWidgets.QLabel(self.status_7)
        self.servo_7.setAlignment(QtCore.Qt.AlignCenter)
        self.servo_7.setObjectName("servo_7")
        self.verticalLayout_24.addWidget(self.servo_7)
        self.position_7 = QtWidgets.QLabel(self.status_7)
        self.position_7.setAlignment(QtCore.Qt.AlignCenter)
        self.position_7.setObjectName("position_7")
        self.verticalLayout_24.addWidget(self.position_7)
        self.speed_7 = QtWidgets.QLabel(self.status_7)
        self.speed_7.setAlignment(QtCore.Qt.AlignCenter)
        self.speed_7.setObjectName("speed_7")
        self.verticalLayout_24.addWidget(self.speed_7)
        self.horizontalLayout_27.addWidget(self.status_7)
        self.status_8 = QtWidgets.QGroupBox(self.frame1)
        self.status_8.setAlignment(QtCore.Qt.AlignCenter)
        self.status_8.setObjectName("status_8")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.status_8)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setSpacing(0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.servo_8 = QtWidgets.QLabel(self.status_8)
        self.servo_8.setAlignment(QtCore.Qt.AlignCenter)
        self.servo_8.setObjectName("servo_8")
        self.verticalLayout_25.addWidget(self.servo_8)
        self.position_8 = QtWidgets.QLabel(self.status_8)
        self.position_8.setAlignment(QtCore.Qt.AlignCenter)
        self.position_8.setObjectName("position_8")
        self.verticalLayout_25.addWidget(self.position_8)
        self.speed_8 = QtWidgets.QLabel(self.status_8)
        self.speed_8.setAlignment(QtCore.Qt.AlignCenter)
        self.speed_8.setObjectName("speed_8")
        self.verticalLayout_25.addWidget(self.speed_8)
        self.horizontalLayout_27.addWidget(self.status_8)
        self.status_9 = QtWidgets.QGroupBox(self.frame1)
        self.status_9.setAlignment(QtCore.Qt.AlignCenter)
        self.status_9.setObjectName("status_9")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.status_9)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setSpacing(0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.servo_9 = QtWidgets.QLabel(self.status_9)
        self.servo_9.setAlignment(QtCore.Qt.AlignCenter)
        self.servo_9.setObjectName("servo_9")
        self.verticalLayout_26.addWidget(self.servo_9)
        self.position_9 = QtWidgets.QLabel(self.status_9)
        self.position_9.setAlignment(QtCore.Qt.AlignCenter)
        self.position_9.setObjectName("position_9")
        self.verticalLayout_26.addWidget(self.position_9)
        self.speed_9 = QtWidgets.QLabel(self.status_9)
        self.speed_9.setAlignment(QtCore.Qt.AlignCenter)
        self.speed_9.setObjectName("speed_9")
        self.verticalLayout_26.addWidget(self.speed_9)
        self.horizontalLayout_27.addWidget(self.status_9)
        self.status_10 = QtWidgets.QGroupBox(self.frame1)
        self.status_10.setAlignment(QtCore.Qt.AlignCenter)
        self.status_10.setObjectName("status_10")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.status_10)
        self.verticalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_27.setSpacing(0)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.servo_10 = QtWidgets.QLabel(self.status_10)
        self.servo_10.setAlignment(QtCore.Qt.AlignCenter)
        self.servo_10.setObjectName("servo_10")
        self.verticalLayout_27.addWidget(self.servo_10)
        self.position_10 = QtWidgets.QLabel(self.status_10)
        self.position_10.setAlignment(QtCore.Qt.AlignCenter)
        self.position_10.setObjectName("position_10")
        self.verticalLayout_27.addWidget(self.position_10)
        self.speed_10 = QtWidgets.QLabel(self.status_10)
        self.speed_10.setAlignment(QtCore.Qt.AlignCenter)
        self.speed_10.setObjectName("speed_10")
        self.verticalLayout_27.addWidget(self.speed_10)
        self.horizontalLayout_27.addWidget(self.status_10)
        self.verticalLayout_33.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setSpacing(0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.status_11 = QtWidgets.QGroupBox(self.frame1)
        self.status_11.setAlignment(QtCore.Qt.AlignCenter)
        self.status_11.setObjectName("status_11")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.status_11)
        self.verticalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_28.setSpacing(0)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.servo_11 = QtWidgets.QLabel(self.status_11)
        self.servo_11.setAlignment(QtCore.Qt.AlignCenter)
        self.servo_11.setObjectName("servo_11")
        self.verticalLayout_28.addWidget(self.servo_11)
        self.position_11 = QtWidgets.QLabel(self.status_11)
        self.position_11.setAlignment(QtCore.Qt.AlignCenter)
        self.position_11.setObjectName("position_11")
        self.verticalLayout_28.addWidget(self.position_11)
        self.speed_11 = QtWidgets.QLabel(self.status_11)
        self.speed_11.setAlignment(QtCore.Qt.AlignCenter)
        self.speed_11.setObjectName("speed_11")
        self.verticalLayout_28.addWidget(self.speed_11)
        self.horizontalLayout_28.addWidget(self.status_11)
        self.status_12 = QtWidgets.QGroupBox(self.frame1)
        self.status_12.setAlignment(QtCore.Qt.AlignCenter)
        self.status_12.setObjectName("status_12")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.status_12)
        self.verticalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_29.setSpacing(0)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.servo_12 = QtWidgets.QLabel(self.status_12)
        self.servo_12.setAlignment(QtCore.Qt.AlignCenter)
        self.servo_12.setObjectName("servo_12")
        self.verticalLayout_29.addWidget(self.servo_12)
        self.position_12 = QtWidgets.QLabel(self.status_12)
        self.position_12.setAlignment(QtCore.Qt.AlignCenter)
        self.position_12.setObjectName("position_12")
        self.verticalLayout_29.addWidget(self.position_12)
        self.speed_12 = QtWidgets.QLabel(self.status_12)
        self.speed_12.setAlignment(QtCore.Qt.AlignCenter)
        self.speed_12.setObjectName("speed_12")
        self.verticalLayout_29.addWidget(self.speed_12)
        self.horizontalLayout_28.addWidget(self.status_12)
        self.status_13 = QtWidgets.QGroupBox(self.frame1)
        self.status_13.setAlignment(QtCore.Qt.AlignCenter)
        self.status_13.setObjectName("status_13")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.status_13)
        self.verticalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_30.setSpacing(0)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.servo_13 = QtWidgets.QLabel(self.status_13)
        self.servo_13.setAlignment(QtCore.Qt.AlignCenter)
        self.servo_13.setObjectName("servo_13")
        self.verticalLayout_30.addWidget(self.servo_13)
        self.position_13 = QtWidgets.QLabel(self.status_13)
        self.position_13.setAlignment(QtCore.Qt.AlignCenter)
        self.position_13.setObjectName("position_13")
        self.verticalLayout_30.addWidget(self.position_13)
        self.speed_13 = QtWidgets.QLabel(self.status_13)
        self.speed_13.setAlignment(QtCore.Qt.AlignCenter)
        self.speed_13.setObjectName("speed_13")
        self.verticalLayout_30.addWidget(self.speed_13)
        self.horizontalLayout_28.addWidget(self.status_13)
        self.status_14 = QtWidgets.QGroupBox(self.frame1)
        self.status_14.setAlignment(QtCore.Qt.AlignCenter)
        self.status_14.setObjectName("status_14")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.status_14)
        self.verticalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_32.setSpacing(0)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.servo_14 = QtWidgets.QLabel(self.status_14)
        self.servo_14.setAlignment(QtCore.Qt.AlignCenter)
        self.servo_14.setObjectName("servo_14")
        self.verticalLayout_32.addWidget(self.servo_14)
        self.position_14 = QtWidgets.QLabel(self.status_14)
        self.position_14.setAlignment(QtCore.Qt.AlignCenter)
        self.position_14.setObjectName("position_14")
        self.verticalLayout_32.addWidget(self.position_14)
        self.speed_14 = QtWidgets.QLabel(self.status_14)
        self.speed_14.setAlignment(QtCore.Qt.AlignCenter)
        self.speed_14.setObjectName("speed_14")
        self.verticalLayout_32.addWidget(self.speed_14)
        self.horizontalLayout_28.addWidget(self.status_14)
        self.verticalLayout_33.addLayout(self.horizontalLayout_28)
        self.verticalLayout_49.addWidget(self.frame1)
        self.stackedWidget.addWidget(self.pg_log)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.frame_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 8)
        MainWindow.setCentralWidget(self.control_window)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "龙骨式连续体机器人操作软件"))
        self.bt_init.setText(_translate("MainWindow", "初始化"))
        self.bt_control.setText(_translate("MainWindow", "操作面板"))
        self.bt_log.setText(_translate("MainWindow", "机器人状态"))
        self.group_usbcan.setTitle(_translate("MainWindow", "【USBCAN卡】"))
        self.bt_open.setText(_translate("MainWindow", "打开设备"))
        self.bx_rate0.setItemText(0, _translate("MainWindow", "250K"))
        self.bx_rate1.setItemText(0, _translate("MainWindow", "250K"))
        self.bt_channel0.setText(_translate("MainWindow", "打开通道0"))
        self.bt_channel1.setText(_translate("MainWindow", "打开通道1"))
        self.bt_reset0.setText(_translate("MainWindow", "重置0"))
        self.bt_reset1.setText(_translate("MainWindow", "重置1"))
        self.bt_close.setText(_translate("MainWindow", "关闭"))
        self.group_motor.setTitle(_translate("MainWindow", "【电机】"))
        self.check_all.setText(_translate("MainWindow", "电机状态确认"))
        self.check_1.setText(_translate("MainWindow", "M1"))
        self.check_2.setText(_translate("MainWindow", "M2"))
        self.check_3.setText(_translate("MainWindow", "M3"))
        self.check_4.setText(_translate("MainWindow", "M4"))
        self.check_5.setText(_translate("MainWindow", "M5"))
        self.check_6.setText(_translate("MainWindow", "M6"))
        self.check_7.setText(_translate("MainWindow", "M7"))
        self.check_8.setText(_translate("MainWindow", "M8"))
        self.check_9.setText(_translate("MainWindow", "M9"))
        self.check_10.setText(_translate("MainWindow", "M10"))
        self.check_11.setText(_translate("MainWindow", "M11"))
        self.check_12.setText(_translate("MainWindow", "M12"))
        self.check_13.setText(_translate("MainWindow", "M13"))
        self.check_14.setText(_translate("MainWindow", "M14"))
        self.r_pos.setText(_translate("MainWindow", "位置模式"))
        self.r_vel.setText(_translate("MainWindow", "速度模式"))
        self.tx_acc.setText(_translate("MainWindow", "加速度"))
        self.le_acc.setPlaceholderText(_translate("MainWindow", "1000"))
        self.tx_dec.setText(_translate("MainWindow", "减速度"))
        self.le_dec.setPlaceholderText(_translate("MainWindow", "10000"))
        self.tx_vel.setText(_translate("MainWindow", "动作速度"))
        self.le_vel.setPlaceholderText(_translate("MainWindow", "100"))
        self.tx_position.setText(_translate("MainWindow", "运动间隔"))
        self.le_position.setPlaceholderText(_translate("MainWindow", "50"))
        self.tx_inhibit.setText(_translate("MainWindow", "禁止时间"))
        self.le_inhibit.setPlaceholderText(_translate("MainWindow", "500"))
        self.bt_save.setText(_translate("MainWindow", "保存"))
        self.bt_launch.setText(_translate("MainWindow", "生效"))
        self.start.setText(_translate("MainWindow", "启动PDO"))
        self.stop.setText(_translate("MainWindow", "停止PDO"))
        self.group_status.setTitle(_translate("MainWindow", "【状态控制】"))
        self.bt_quick_stop.setText(_translate("MainWindow", "急停"))
        self.bt_unlock.setText(_translate("MainWindow", "解除抱闸"))
        self.bt_enable.setText(_translate("MainWindow", "伺服使能"))
        self.group_control.setTitle(_translate("MainWindow", "【遥操作】"))
        self.bt_joint_control.setText(_translate("MainWindow", "关节操作"))
        self.bt_quit.setText(_translate("MainWindow", "退出"))
        self.group_1.setTitle(_translate("MainWindow", "1"))
        self.bt_negative_1.setText(_translate("MainWindow", "-"))
        self.bt_positive_1.setText(_translate("MainWindow", "+"))
        self.group_2.setTitle(_translate("MainWindow", "2"))
        self.bt_negative_2.setText(_translate("MainWindow", "-"))
        self.bt_positive_2.setText(_translate("MainWindow", "+"))
        self.group_3.setTitle(_translate("MainWindow", "3"))
        self.bt_negative_3.setText(_translate("MainWindow", "-"))
        self.bt_positive_3.setText(_translate("MainWindow", "+"))
        self.group_4.setTitle(_translate("MainWindow", "4"))
        self.bt_negative_4.setText(_translate("MainWindow", "-"))
        self.bt_positive_4.setText(_translate("MainWindow", "+"))
        self.group_5.setTitle(_translate("MainWindow", "5"))
        self.bt_negative_5.setText(_translate("MainWindow", "-"))
        self.bt_positive_5.setText(_translate("MainWindow", "+"))
        self.group_6.setTitle(_translate("MainWindow", "6"))
        self.bt_negative_6.setText(_translate("MainWindow", "-"))
        self.bt_positive_6.setText(_translate("MainWindow", "+"))
        self.group_7.setTitle(_translate("MainWindow", "7"))
        self.bt_negative_7.setText(_translate("MainWindow", "-"))
        self.bt_positive_7.setText(_translate("MainWindow", "+"))
        self.group_8.setTitle(_translate("MainWindow", "8"))
        self.bt_negative_8.setText(_translate("MainWindow", "-"))
        self.bt_positive_8.setText(_translate("MainWindow", "+"))
        self.group_9.setTitle(_translate("MainWindow", "9"))
        self.bt_negative_9.setText(_translate("MainWindow", "-"))
        self.bt_positive_9.setText(_translate("MainWindow", "+"))
        self.group_10.setTitle(_translate("MainWindow", "10"))
        self.bt_negative_10.setText(_translate("MainWindow", "-"))
        self.bt_positive_10.setText(_translate("MainWindow", "+"))
        self.group_11.setTitle(_translate("MainWindow", "11"))
        self.bt_negative_11.setText(_translate("MainWindow", "-"))
        self.bt_positive_11.setText(_translate("MainWindow", "+"))
        self.group_12.setTitle(_translate("MainWindow", "12"))
        self.bt_negative_12.setText(_translate("MainWindow", "-"))
        self.bt_positive_12.setText(_translate("MainWindow", "+"))
        self.group_13.setTitle(_translate("MainWindow", "13"))
        self.bt_negative_13.setText(_translate("MainWindow", "-"))
        self.bt_positive_13.setText(_translate("MainWindow", "+"))
        self.group_14.setTitle(_translate("MainWindow", "14"))
        self.bt_negative_14.setText(_translate("MainWindow", "-"))
        self.bt_positive_14.setText(_translate("MainWindow", "+"))
        self.bt_end_control.setText(_translate("MainWindow", "末端操作"))
        self.bt_exit.setText(_translate("MainWindow", "退出"))
        self.status_1.setTitle(_translate("MainWindow", "1"))
        self.servo_1.setText(_translate("MainWindow", "servo"))
        self.position_1.setText(_translate("MainWindow", "position"))
        self.speed_1.setText(_translate("MainWindow", "speed"))
        self.status_2.setTitle(_translate("MainWindow", "2"))
        self.servo_2.setText(_translate("MainWindow", "servo"))
        self.position_2.setText(_translate("MainWindow", "position"))
        self.speed_2.setText(_translate("MainWindow", "speed"))
        self.status_3.setTitle(_translate("MainWindow", "3"))
        self.servo_3.setText(_translate("MainWindow", "servo"))
        self.position_3.setText(_translate("MainWindow", "position"))
        self.speed_3.setText(_translate("MainWindow", "speed"))
        self.status_4.setTitle(_translate("MainWindow", "4"))
        self.servo_4.setText(_translate("MainWindow", "servo"))
        self.position_4.setText(_translate("MainWindow", "position"))
        self.speed_4.setText(_translate("MainWindow", "speed"))
        self.status_5.setTitle(_translate("MainWindow", "5"))
        self.servo_5.setText(_translate("MainWindow", "servo"))
        self.position_5.setText(_translate("MainWindow", "position"))
        self.speed_5.setText(_translate("MainWindow", "speed"))
        self.status_6.setTitle(_translate("MainWindow", "6"))
        self.servo_6.setText(_translate("MainWindow", "servo"))
        self.position_6.setText(_translate("MainWindow", "position"))
        self.speed_6.setText(_translate("MainWindow", "speed"))
        self.status_7.setTitle(_translate("MainWindow", "7"))
        self.servo_7.setText(_translate("MainWindow", "servo"))
        self.position_7.setText(_translate("MainWindow", "position"))
        self.speed_7.setText(_translate("MainWindow", "speed"))
        self.status_8.setTitle(_translate("MainWindow", "8"))
        self.servo_8.setText(_translate("MainWindow", "servo"))
        self.position_8.setText(_translate("MainWindow", "position"))
        self.speed_8.setText(_translate("MainWindow", "speed"))
        self.status_9.setTitle(_translate("MainWindow", "9"))
        self.servo_9.setText(_translate("MainWindow", "servo"))
        self.position_9.setText(_translate("MainWindow", "position"))
        self.speed_9.setText(_translate("MainWindow", "speed"))
        self.status_10.setTitle(_translate("MainWindow", "10"))
        self.servo_10.setText(_translate("MainWindow", "servo"))
        self.position_10.setText(_translate("MainWindow", "position"))
        self.speed_10.setText(_translate("MainWindow", "speed"))
        self.status_11.setTitle(_translate("MainWindow", "11"))
        self.servo_11.setText(_translate("MainWindow", "servo"))
        self.position_11.setText(_translate("MainWindow", "position"))
        self.speed_11.setText(_translate("MainWindow", "speed"))
        self.status_12.setTitle(_translate("MainWindow", "12"))
        self.servo_12.setText(_translate("MainWindow", "servo"))
        self.position_12.setText(_translate("MainWindow", "position"))
        self.speed_12.setText(_translate("MainWindow", "speed"))
        self.status_13.setTitle(_translate("MainWindow", "13"))
        self.servo_13.setText(_translate("MainWindow", "servo"))
        self.position_13.setText(_translate("MainWindow", "position"))
        self.speed_13.setText(_translate("MainWindow", "speed"))
        self.status_14.setTitle(_translate("MainWindow", "14"))
        self.servo_14.setText(_translate("MainWindow", "servo"))
        self.position_14.setText(_translate("MainWindow", "position"))
        self.speed_14.setText(_translate("MainWindow", "speed"))
