# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/login.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(788, 506)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.login_window = QtWidgets.QWidget(MainWindow)
        self.login_window.setEnabled(True)
        self.login_window.setObjectName("login_window")
        self.bg_login = QtWidgets.QLabel(self.login_window)
        self.bg_login.setGeometry(QtCore.QRect(-20, -10, 381, 641))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bg_login.sizePolicy().hasHeightForWidth())
        self.bg_login.setSizePolicy(sizePolicy)
        self.bg_login.setStyleSheet("background-color: rgb(85, 87, 83);")
        self.bg_login.setText("")
        self.bg_login.setObjectName("bg_login")
        self.bg_image = QtWidgets.QLabel(self.login_window)
        self.bg_image.setGeometry(QtCore.QRect(360, -10, 941, 641))
        self.bg_image.setStyleSheet("background-image: url(:/images/连续体机器人.jpg);")
        self.bg_image.setText("")
        self.bg_image.setObjectName("bg_image")
        self.bg_trans = QtWidgets.QLabel(self.login_window)
        self.bg_trans.setGeometry(QtCore.QRect(360, -10, 941, 641))
        self.bg_trans.setStyleSheet("background-color: rgba(0, 0, 0,150);")
        self.bg_trans.setText("")
        self.bg_trans.setObjectName("bg_trans")
        self.title_main = QtWidgets.QLabel(self.login_window)
        self.title_main.setGeometry(QtCore.QRect(400, 30, 351, 211))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.title_main.setFont(font)
        self.title_main.setStyleSheet("color: rgba(252, 175, 62, 200);")
        self.title_main.setObjectName("title_main")
        self.version = QtWidgets.QLabel(self.login_window)
        self.version.setGeometry(QtCore.QRect(640, 450, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.version.setFont(font)
        self.version.setStyleSheet("color: rgb(211, 215, 207);")
        self.version.setObjectName("version")
        self.title = QtWidgets.QLabel(self.login_window)
        self.title.setGeometry(QtCore.QRect(90, 50, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.title.setFont(font)
        self.title.setStyleSheet("color: rgb(252, 175, 62);")
        self.title.setObjectName("title")
        self.button_login = QtWidgets.QPushButton(self.login_window)
        self.button_login.setGeometry(QtCore.QRect(90, 390, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.button_login.setFont(font)
        self.button_login.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.button_login.setObjectName("button_login")
        self.box_user = QtWidgets.QComboBox(self.login_window)
        self.box_user.setGeometry(QtCore.QRect(30, 230, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.box_user.setFont(font)
        self.box_user.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.box_user.setObjectName("box_user")
        self.box_user.addItem("")
        self.box_user.addItem("")
        self.tx_1 = QtWidgets.QLabel(self.login_window)
        self.tx_1.setGeometry(QtCore.QRect(60, 130, 221, 41))
        self.tx_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.tx_1.setObjectName("tx_1")
        self.tx_2 = QtWidgets.QLabel(self.login_window)
        self.tx_2.setGeometry(QtCore.QRect(60, 180, 221, 41))
        self.tx_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.tx_2.setObjectName("tx_2")
        self.password = QtWidgets.QLineEdit(self.login_window)
        self.password.setGeometry(QtCore.QRect(30, 290, 301, 51))
        self.password.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.password.setObjectName("password")
        self.bg_image.raise_()
        self.bg_trans.raise_()
        self.bg_login.raise_()
        self.title_main.raise_()
        self.version.raise_()
        self.title.raise_()
        self.button_login.raise_()
        self.box_user.raise_()
        self.tx_1.raise_()
        self.tx_2.raise_()
        self.password.raise_()
        MainWindow.setCentralWidget(self.login_window)
        self.action1 = QtWidgets.QAction(MainWindow)
        self.action1.setObjectName("action1")
        self.action2 = QtWidgets.QAction(MainWindow)
        self.action2.setObjectName("action2")
        self.action3 = QtWidgets.QAction(MainWindow)
        self.action3.setObjectName("action3")
        self.action4 = QtWidgets.QAction(MainWindow)
        self.action4.setObjectName("action4")
        self.action5 = QtWidgets.QAction(MainWindow)
        self.action5.setObjectName("action5")
        self.action6 = QtWidgets.QAction(MainWindow)
        self.action6.setObjectName("action6")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "连续体机器人"))
        self.title_main.setText(_translate("MainWindow", "连续体机器人"))
        self.version.setText(_translate("MainWindow", "Version 1.0"))
        self.title.setText(_translate("MainWindow", "欢迎使用"))
        self.button_login.setText(_translate("MainWindow", "登录"))
        self.box_user.setItemText(0, _translate("MainWindow", "测试人员"))
        self.box_user.setItemText(1, _translate("MainWindow", "管理员"))
        self.tx_1.setText(_translate("MainWindow", "测试人员：默认操控模式"))
        self.tx_2.setText(_translate("MainWindow", "管理员：可更改底层信息"))
        self.password.setPlaceholderText(_translate("MainWindow", "请输入密码："))
        self.action1.setText(_translate("MainWindow", "1"))
        self.action2.setText(_translate("MainWindow", "2"))
        self.action3.setText(_translate("MainWindow", "3"))
        self.action4.setText(_translate("MainWindow", "4"))
        self.action5.setText(_translate("MainWindow", "5"))
        self.action6.setText(_translate("MainWindow", "6"))
import resourece_rc
