# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/control.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(847, 610)
        MainWindow.setStyleSheet("")
        self.control_window = QtWidgets.QWidget(MainWindow)
        self.control_window.setStyleSheet("QWidget {\n"
"    background-color: rgb(56, 57, 60);\n"
"}\n"
"\n"
"\n"
"QFrame {\n"
"    background-color: rgb(86, 88, 93);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"\n"
"QPushButton {\n"
"    background-color: rgb(114, 159, 207);\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:disabled {\n"
"    color: gray;\n"
"    background-color: rgb(86, 88, 93);\n"
"}\n"
"\n"
"QStackedWidget > QWidget {\n"
"    background-color: rgb(86, 88, 93);\n"
"    border-radius: 10px;\n"
"}\n"
"QStackedWidget QLabel {\n"
"    color: white;\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"}\n"
"QStackedWidget QLabel:disabled {\n"
"    color: gray;\n"
"}\n"
"\n"
"QStackedWidget QPushButton {\n"
"    background-color: rgb(114, 159, 207);\n"
"    font-size: 25px;\n"
"}\n"
"\n"
"QStackedWidget QRadioButton:disabled {\n"
"    font-size: 20px;\n"
"    color: gray;\n"
"    font-weight: bold;\n"
"    background-color: rgb(86, 88, 93);\n"
"}\n"
"QStackedWidget QRadioButton {\n"
"    font-size: 20px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    background-color: rgb(86, 88, 93);\n"
"}\n"
"\n"
"QStackedWidget QLineEdit {\n"
"    font-size: 20px;\n"
"    color: white;\n"
"    background-color: rgb(86, 88, 93);\n"
"}\n"
"\n"
"QStackedWidget QGroupBox {\n"
"    font-size: 20px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    background-color: rgb(86, 88, 93);\n"
"}\n"
"QStackedWidget QGroupBox:disabled {\n"
"    color: gray;\n"
"}\n"
"\n"
"QStackedWidget QComboBox {\n"
"    color: white;\n"
"    background-color: rgb(114, 159, 207);\n"
"    font-size: 25px;\n"
"    font-weight: bold;\n"
"    border-radius: 10px;\n"
"}\n"
"QStackedWidget QComboBox:disabled {\n"
"    background-color: rgb(86, 88, 93);\n"
"    color: gray;\n"
"}\n"
"\n"
"QStackedWidget QTextBrowser {\n"
"    color: white;\n"
"    font-size: 20px;\n"
"}")
        self.control_window.setObjectName("control_window")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.control_window)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.control_window)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bt_init = QtWidgets.QPushButton(self.frame)
        self.bt_init.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_init.sizePolicy().hasHeightForWidth())
        self.bt_init.setSizePolicy(sizePolicy)
        self.bt_init.setObjectName("bt_init")
        self.horizontalLayout.addWidget(self.bt_init)
        self.bt_control = QtWidgets.QPushButton(self.frame)
        self.bt_control.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_control.sizePolicy().hasHeightForWidth())
        self.bt_control.setSizePolicy(sizePolicy)
        self.bt_control.setObjectName("bt_control")
        self.horizontalLayout.addWidget(self.bt_control)
        self.bt_log = QtWidgets.QPushButton(self.frame)
        self.bt_log.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_log.sizePolicy().hasHeightForWidth())
        self.bt_log.setSizePolicy(sizePolicy)
        self.bt_log.setObjectName("bt_log")
        self.horizontalLayout.addWidget(self.bt_log)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.control_window)
        self.frame_2.setEnabled(True)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.pg_init = QtWidgets.QWidget()
        self.pg_init.setObjectName("pg_init")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.pg_init)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.group_usbcan = QtWidgets.QGroupBox(self.pg_init)
        self.group_usbcan.setObjectName("group_usbcan")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.group_usbcan)
        self.horizontalLayout_2.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bt_open = QtWidgets.QPushButton(self.group_usbcan)
        self.bt_open.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_open.sizePolicy().hasHeightForWidth())
        self.bt_open.setSizePolicy(sizePolicy)
        self.bt_open.setObjectName("bt_open")
        self.horizontalLayout_2.addWidget(self.bt_open)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.bx_rate0 = QtWidgets.QComboBox(self.group_usbcan)
        self.bx_rate0.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bx_rate0.sizePolicy().hasHeightForWidth())
        self.bx_rate0.setSizePolicy(sizePolicy)
        self.bx_rate0.setObjectName("bx_rate0")
        self.bx_rate0.addItem("")
        self.verticalLayout_4.addWidget(self.bx_rate0)
        self.bx_rate1 = QtWidgets.QComboBox(self.group_usbcan)
        self.bx_rate1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bx_rate1.sizePolicy().hasHeightForWidth())
        self.bx_rate1.setSizePolicy(sizePolicy)
        self.bx_rate1.setObjectName("bx_rate1")
        self.bx_rate1.addItem("")
        self.verticalLayout_4.addWidget(self.bx_rate1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(15)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.bt_channel0 = QtWidgets.QPushButton(self.group_usbcan)
        self.bt_channel0.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_channel0.sizePolicy().hasHeightForWidth())
        self.bt_channel0.setSizePolicy(sizePolicy)
        self.bt_channel0.setObjectName("bt_channel0")
        self.verticalLayout_5.addWidget(self.bt_channel0)
        self.bt_channel1 = QtWidgets.QPushButton(self.group_usbcan)
        self.bt_channel1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_channel1.sizePolicy().hasHeightForWidth())
        self.bt_channel1.setSizePolicy(sizePolicy)
        self.bt_channel1.setObjectName("bt_channel1")
        self.verticalLayout_5.addWidget(self.bt_channel1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_50 = QtWidgets.QVBoxLayout()
        self.verticalLayout_50.setSpacing(15)
        self.verticalLayout_50.setObjectName("verticalLayout_50")
        self.bt_reset0 = QtWidgets.QPushButton(self.group_usbcan)
        self.bt_reset0.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_reset0.sizePolicy().hasHeightForWidth())
        self.bt_reset0.setSizePolicy(sizePolicy)
        self.bt_reset0.setObjectName("bt_reset0")
        self.verticalLayout_50.addWidget(self.bt_reset0)
        self.bt_reset1 = QtWidgets.QPushButton(self.group_usbcan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_reset1.sizePolicy().hasHeightForWidth())
        self.bt_reset1.setSizePolicy(sizePolicy)
        self.bt_reset1.setObjectName("bt_reset1")
        self.verticalLayout_50.addWidget(self.bt_reset1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_50)
        self.bt_close = QtWidgets.QPushButton(self.group_usbcan)
        self.bt_close.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_close.sizePolicy().hasHeightForWidth())
        self.bt_close.setSizePolicy(sizePolicy)
        self.bt_close.setObjectName("bt_close")
        self.horizontalLayout_2.addWidget(self.bt_close)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 2)
        self.horizontalLayout_2.setStretch(3, 1)
        self.horizontalLayout_2.setStretch(4, 1)
        self.verticalLayout_7.addWidget(self.group_usbcan)
        self.group_motor = QtWidgets.QGroupBox(self.pg_init)
        self.group_motor.setEnabled(True)
        self.group_motor.setObjectName("group_motor")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.group_motor)
        self.verticalLayout_13.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_13.setSpacing(6)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_5 = QtWidgets.QFrame(self.group_motor)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(10)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.frame_8 = QtWidgets.QFrame(self.frame_5)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(10)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.check_all = QtWidgets.QPushButton(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_all.sizePolicy().hasHeightForWidth())
        self.check_all.setSizePolicy(sizePolicy)
        self.check_all.setMinimumSize(QtCore.QSize(0, 0))
        self.check_all.setObjectName("check_all")
        self.horizontalLayout_13.addWidget(self.check_all)
        self.start = QtWidgets.QPushButton(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start.sizePolicy().hasHeightForWidth())
        self.start.setSizePolicy(sizePolicy)
        self.start.setObjectName("start")
        self.horizontalLayout_13.addWidget(self.start)
        self.horizontalLayout_13.setStretch(0, 3)
        self.horizontalLayout_13.setStretch(1, 1)
        self.verticalLayout_19.addWidget(self.frame_8)
        self.frame_4 = QtWidgets.QFrame(self.frame_5)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.check_1 = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_1.sizePolicy().hasHeightForWidth())
        self.check_1.setSizePolicy(sizePolicy)
        self.check_1.setObjectName("check_1")
        self.horizontalLayout_3.addWidget(self.check_1)
        self.check_2 = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_2.sizePolicy().hasHeightForWidth())
        self.check_2.setSizePolicy(sizePolicy)
        self.check_2.setObjectName("check_2")
        self.horizontalLayout_3.addWidget(self.check_2)
        self.check_3 = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_3.sizePolicy().hasHeightForWidth())
        self.check_3.setSizePolicy(sizePolicy)
        self.check_3.setObjectName("check_3")
        self.horizontalLayout_3.addWidget(self.check_3)
        self.check_4 = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_4.sizePolicy().hasHeightForWidth())
        self.check_4.setSizePolicy(sizePolicy)
        self.check_4.setObjectName("check_4")
        self.horizontalLayout_3.addWidget(self.check_4)
        self.check_5 = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_5.sizePolicy().hasHeightForWidth())
        self.check_5.setSizePolicy(sizePolicy)
        self.check_5.setObjectName("check_5")
        self.horizontalLayout_3.addWidget(self.check_5)
        self.check_6 = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_6.sizePolicy().hasHeightForWidth())
        self.check_6.setSizePolicy(sizePolicy)
        self.check_6.setObjectName("check_6")
        self.horizontalLayout_3.addWidget(self.check_6)
        self.check_7 = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_7.sizePolicy().hasHeightForWidth())
        self.check_7.setSizePolicy(sizePolicy)
        self.check_7.setObjectName("check_7")
        self.horizontalLayout_3.addWidget(self.check_7)
        self.check_8 = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_8.sizePolicy().hasHeightForWidth())
        self.check_8.setSizePolicy(sizePolicy)
        self.check_8.setObjectName("check_8")
        self.horizontalLayout_3.addWidget(self.check_8)
        self.check_9 = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_9.sizePolicy().hasHeightForWidth())
        self.check_9.setSizePolicy(sizePolicy)
        self.check_9.setObjectName("check_9")
        self.horizontalLayout_3.addWidget(self.check_9)
        self.check_10 = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_10.sizePolicy().hasHeightForWidth())
        self.check_10.setSizePolicy(sizePolicy)
        self.check_10.setObjectName("check_10")
        self.horizontalLayout_3.addWidget(self.check_10)
        self.verticalLayout_19.addWidget(self.frame_4)
        self.verticalLayout_13.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.group_motor)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(7)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.frame_3 = QtWidgets.QFrame(self.frame_6)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(7)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(15, -1, 15, -1)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.r_pos = QtWidgets.QRadioButton(self.frame_3)
        self.r_pos.setEnabled(True)
        self.r_pos.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.r_pos.setCheckable(True)
        self.r_pos.setChecked(True)
        self.r_pos.setObjectName("r_pos")
        self.verticalLayout_6.addWidget(self.r_pos)
        self.r_vel = QtWidgets.QRadioButton(self.frame_3)
        self.r_vel.setEnabled(True)
        self.r_vel.setChecked(False)
        self.r_vel.setObjectName("r_vel")
        self.verticalLayout_6.addWidget(self.r_vel)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_8.setSpacing(10)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tx_acc = QtWidgets.QLabel(self.frame_3)
        self.tx_acc.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_acc.sizePolicy().hasHeightForWidth())
        self.tx_acc.setSizePolicy(sizePolicy)
        self.tx_acc.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_acc.setObjectName("tx_acc")
        self.verticalLayout_8.addWidget(self.tx_acc)
        self.le_acc = QtWidgets.QLineEdit(self.frame_3)
        self.le_acc.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_acc.sizePolicy().hasHeightForWidth())
        self.le_acc.setSizePolicy(sizePolicy)
        self.le_acc.setAlignment(QtCore.Qt.AlignCenter)
        self.le_acc.setObjectName("le_acc")
        self.verticalLayout_8.addWidget(self.le_acc)
        self.horizontalLayout_5.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_9.setSpacing(10)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tx_dec = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_dec.sizePolicy().hasHeightForWidth())
        self.tx_dec.setSizePolicy(sizePolicy)
        self.tx_dec.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_dec.setObjectName("tx_dec")
        self.verticalLayout_9.addWidget(self.tx_dec)
        self.le_dec = QtWidgets.QLineEdit(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_dec.sizePolicy().hasHeightForWidth())
        self.le_dec.setSizePolicy(sizePolicy)
        self.le_dec.setAlignment(QtCore.Qt.AlignCenter)
        self.le_dec.setObjectName("le_dec")
        self.verticalLayout_9.addWidget(self.le_dec)
        self.horizontalLayout_5.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_10.setSpacing(10)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.tx_vel = QtWidgets.QLabel(self.frame_3)
        self.tx_vel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_vel.sizePolicy().hasHeightForWidth())
        self.tx_vel.setSizePolicy(sizePolicy)
        self.tx_vel.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_vel.setObjectName("tx_vel")
        self.verticalLayout_10.addWidget(self.tx_vel)
        self.le_vel = QtWidgets.QLineEdit(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_vel.sizePolicy().hasHeightForWidth())
        self.le_vel.setSizePolicy(sizePolicy)
        self.le_vel.setAlignment(QtCore.Qt.AlignCenter)
        self.le_vel.setObjectName("le_vel")
        self.verticalLayout_10.addWidget(self.le_vel)
        self.horizontalLayout_5.addLayout(self.verticalLayout_10)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_21.setSpacing(10)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.tx_position = QtWidgets.QLabel(self.frame_3)
        self.tx_position.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_position.sizePolicy().hasHeightForWidth())
        self.tx_position.setSizePolicy(sizePolicy)
        self.tx_position.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_position.setObjectName("tx_position")
        self.verticalLayout_21.addWidget(self.tx_position)
        self.le_position = QtWidgets.QLineEdit(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_position.sizePolicy().hasHeightForWidth())
        self.le_position.setSizePolicy(sizePolicy)
        self.le_position.setAlignment(QtCore.Qt.AlignCenter)
        self.le_position.setObjectName("le_position")
        self.verticalLayout_21.addWidget(self.le_position)
        self.horizontalLayout_5.addLayout(self.verticalLayout_21)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_11.setSpacing(10)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.tx_inhibit = QtWidgets.QLabel(self.frame_3)
        self.tx_inhibit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_inhibit.sizePolicy().hasHeightForWidth())
        self.tx_inhibit.setSizePolicy(sizePolicy)
        self.tx_inhibit.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_inhibit.setObjectName("tx_inhibit")
        self.verticalLayout_11.addWidget(self.tx_inhibit)
        self.le_inhibit = QtWidgets.QLineEdit(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_inhibit.sizePolicy().hasHeightForWidth())
        self.le_inhibit.setSizePolicy(sizePolicy)
        self.le_inhibit.setAlignment(QtCore.Qt.AlignCenter)
        self.le_inhibit.setObjectName("le_inhibit")
        self.verticalLayout_11.addWidget(self.le_inhibit)
        self.horizontalLayout_5.addLayout(self.verticalLayout_11)
        self.verticalLayout_51 = QtWidgets.QVBoxLayout()
        self.verticalLayout_51.setSpacing(10)
        self.verticalLayout_51.setObjectName("verticalLayout_51")
        self.bt_save = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_save.sizePolicy().hasHeightForWidth())
        self.bt_save.setSizePolicy(sizePolicy)
        self.bt_save.setObjectName("bt_save")
        self.verticalLayout_51.addWidget(self.bt_save)
        self.bt_launch = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_launch.sizePolicy().hasHeightForWidth())
        self.bt_launch.setSizePolicy(sizePolicy)
        self.bt_launch.setObjectName("bt_launch")
        self.verticalLayout_51.addWidget(self.bt_launch)
        self.horizontalLayout_5.addLayout(self.verticalLayout_51)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 2)
        self.horizontalLayout_5.setStretch(2, 2)
        self.horizontalLayout_5.setStretch(3, 2)
        self.horizontalLayout_5.setStretch(4, 2)
        self.horizontalLayout_5.setStretch(5, 2)
        self.horizontalLayout_5.setStretch(6, 2)
        self.verticalLayout_20.addWidget(self.frame_3)
        self.verticalLayout_13.addWidget(self.frame_6)
        self.verticalLayout_7.addWidget(self.group_motor)
        self.group_io = QtWidgets.QGroupBox(self.pg_init)
        self.group_io.setObjectName("group_io")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.group_io)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_31 = QtWidgets.QFrame(self.group_io)
        self.frame_31.setObjectName("frame_31")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_31)
        self.horizontalLayout_7.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_7.setSpacing(20)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.bt_check = QtWidgets.QPushButton(self.frame_31)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_check.sizePolicy().hasHeightForWidth())
        self.bt_check.setSizePolicy(sizePolicy)
        self.bt_check.setObjectName("bt_check")
        self.horizontalLayout_7.addWidget(self.bt_check)
        self.bt_start = QtWidgets.QPushButton(self.frame_31)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_start.sizePolicy().hasHeightForWidth())
        self.bt_start.setSizePolicy(sizePolicy)
        self.bt_start.setObjectName("bt_start")
        self.horizontalLayout_7.addWidget(self.bt_start)
        self.horizontalLayout_6.addWidget(self.frame_31)
        self.groupBox_7 = QtWidgets.QGroupBox(self.group_io)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_6.addWidget(self.groupBox_7)
        self.verticalLayout_7.addWidget(self.group_io)
        self.verticalLayout_7.setStretch(0, 2)
        self.verticalLayout_7.setStretch(1, 5)
        self.verticalLayout_7.setStretch(2, 2)
        self.stackedWidget.addWidget(self.pg_init)
        self.pg_control = QtWidgets.QWidget()
        self.pg_control.setObjectName("pg_control")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.pg_control)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.group_status = QtWidgets.QGroupBox(self.pg_control)
        self.group_status.setObjectName("group_status")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.group_status)
        self.horizontalLayout_9.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_9.setSpacing(5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.bt_quick_stop = QtWidgets.QPushButton(self.group_status)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_quick_stop.sizePolicy().hasHeightForWidth())
        self.bt_quick_stop.setSizePolicy(sizePolicy)
        self.bt_quick_stop.setObjectName("bt_quick_stop")
        self.horizontalLayout_9.addWidget(self.bt_quick_stop)
        self.frame_51 = QtWidgets.QFrame(self.group_status)
        self.frame_51.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_51.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_51.setObjectName("frame_51")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_51)
        self.verticalLayout_23.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout_23.setSpacing(10)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.bt_unlock_all = QtWidgets.QPushButton(self.frame_51)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_unlock_all.sizePolicy().hasHeightForWidth())
        self.bt_unlock_all.setSizePolicy(sizePolicy)
        self.bt_unlock_all.setObjectName("bt_unlock_all")
        self.verticalLayout_23.addWidget(self.bt_unlock_all)
        self.frame_61 = QtWidgets.QFrame(self.frame_51)
        self.frame_61.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_61.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_61.setObjectName("frame_61")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_61)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(10)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.bt_unlock_1 = QtWidgets.QPushButton(self.frame_61)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_unlock_1.sizePolicy().hasHeightForWidth())
        self.bt_unlock_1.setSizePolicy(sizePolicy)
        self.bt_unlock_1.setObjectName("bt_unlock_1")
        self.horizontalLayout_8.addWidget(self.bt_unlock_1)
        self.bt_unlock_2 = QtWidgets.QPushButton(self.frame_61)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_unlock_2.sizePolicy().hasHeightForWidth())
        self.bt_unlock_2.setSizePolicy(sizePolicy)
        self.bt_unlock_2.setObjectName("bt_unlock_2")
        self.horizontalLayout_8.addWidget(self.bt_unlock_2)
        self.bt_unlock_3 = QtWidgets.QPushButton(self.frame_61)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_unlock_3.sizePolicy().hasHeightForWidth())
        self.bt_unlock_3.setSizePolicy(sizePolicy)
        self.bt_unlock_3.setObjectName("bt_unlock_3")
        self.horizontalLayout_8.addWidget(self.bt_unlock_3)
        self.bt_unlock_4 = QtWidgets.QPushButton(self.frame_61)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_unlock_4.sizePolicy().hasHeightForWidth())
        self.bt_unlock_4.setSizePolicy(sizePolicy)
        self.bt_unlock_4.setObjectName("bt_unlock_4")
        self.horizontalLayout_8.addWidget(self.bt_unlock_4)
        self.bt_unlock_5 = QtWidgets.QPushButton(self.frame_61)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_unlock_5.sizePolicy().hasHeightForWidth())
        self.bt_unlock_5.setSizePolicy(sizePolicy)
        self.bt_unlock_5.setObjectName("bt_unlock_5")
        self.horizontalLayout_8.addWidget(self.bt_unlock_5)
        self.bt_unlock_6 = QtWidgets.QPushButton(self.frame_61)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_unlock_6.sizePolicy().hasHeightForWidth())
        self.bt_unlock_6.setSizePolicy(sizePolicy)
        self.bt_unlock_6.setObjectName("bt_unlock_6")
        self.horizontalLayout_8.addWidget(self.bt_unlock_6)
        self.bt_unlock_7 = QtWidgets.QPushButton(self.frame_61)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_unlock_7.sizePolicy().hasHeightForWidth())
        self.bt_unlock_7.setSizePolicy(sizePolicy)
        self.bt_unlock_7.setObjectName("bt_unlock_7")
        self.horizontalLayout_8.addWidget(self.bt_unlock_7)
        self.bt_unlock_8 = QtWidgets.QPushButton(self.frame_61)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_unlock_8.sizePolicy().hasHeightForWidth())
        self.bt_unlock_8.setSizePolicy(sizePolicy)
        self.bt_unlock_8.setObjectName("bt_unlock_8")
        self.horizontalLayout_8.addWidget(self.bt_unlock_8)
        self.bt_unlock_9 = QtWidgets.QPushButton(self.frame_61)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_unlock_9.sizePolicy().hasHeightForWidth())
        self.bt_unlock_9.setSizePolicy(sizePolicy)
        self.bt_unlock_9.setObjectName("bt_unlock_9")
        self.horizontalLayout_8.addWidget(self.bt_unlock_9)
        self.bt_unlock_10 = QtWidgets.QPushButton(self.frame_61)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_unlock_10.sizePolicy().hasHeightForWidth())
        self.bt_unlock_10.setSizePolicy(sizePolicy)
        self.bt_unlock_10.setObjectName("bt_unlock_10")
        self.horizontalLayout_8.addWidget(self.bt_unlock_10)
        self.verticalLayout_23.addWidget(self.frame_61)
        self.verticalLayout_23.setStretch(0, 1)
        self.verticalLayout_23.setStretch(1, 1)
        self.horizontalLayout_9.addWidget(self.frame_51)
        self.bt_enable = QtWidgets.QPushButton(self.group_status)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_enable.sizePolicy().hasHeightForWidth())
        self.bt_enable.setSizePolicy(sizePolicy)
        self.bt_enable.setObjectName("bt_enable")
        self.horizontalLayout_9.addWidget(self.bt_enable)
        self.horizontalLayout_9.setStretch(0, 1)
        self.horizontalLayout_9.setStretch(1, 5)
        self.horizontalLayout_9.setStretch(2, 1)
        self.verticalLayout_22.addWidget(self.group_status)
        self.group_single = QtWidgets.QGroupBox(self.pg_control)
        self.group_single.setObjectName("group_single")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.group_single)
        self.horizontalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSpacing(10)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label = QtWidgets.QLabel(self.group_single)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_12.addWidget(self.label)
        self.pushButton_2 = QtWidgets.QPushButton(self.group_single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_12.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.group_single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_12.addWidget(self.pushButton_3)
        self.verticalLayout_12.setStretch(0, 1)
        self.verticalLayout_12.setStretch(1, 2)
        self.verticalLayout_12.setStretch(2, 2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_12)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setSpacing(10)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_3 = QtWidgets.QLabel(self.group_single)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_14.addWidget(self.label_3)
        self.pushButton_6 = QtWidgets.QPushButton(self.group_single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_14.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.group_single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_14.addWidget(self.pushButton_7)
        self.verticalLayout_14.setStretch(0, 1)
        self.verticalLayout_14.setStretch(1, 2)
        self.verticalLayout_14.setStretch(2, 2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setSpacing(10)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_4 = QtWidgets.QLabel(self.group_single)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_15.addWidget(self.label_4)
        self.pushButton_8 = QtWidgets.QPushButton(self.group_single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_15.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.group_single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_15.addWidget(self.pushButton_9)
        self.verticalLayout_15.setStretch(0, 1)
        self.verticalLayout_15.setStretch(1, 2)
        self.verticalLayout_15.setStretch(2, 2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_15)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setSpacing(10)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_5 = QtWidgets.QLabel(self.group_single)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_16.addWidget(self.label_5)
        self.pushButton_10 = QtWidgets.QPushButton(self.group_single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_16.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.group_single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_16.addWidget(self.pushButton_11)
        self.verticalLayout_16.setStretch(0, 1)
        self.verticalLayout_16.setStretch(1, 2)
        self.verticalLayout_16.setStretch(2, 2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_16)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setSpacing(10)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_6 = QtWidgets.QLabel(self.group_single)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_17.addWidget(self.label_6)
        self.pushButton_12 = QtWidgets.QPushButton(self.group_single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_17.addWidget(self.pushButton_12)
        self.pushButton_13 = QtWidgets.QPushButton(self.group_single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_13.sizePolicy().hasHeightForWidth())
        self.pushButton_13.setSizePolicy(sizePolicy)
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_17.addWidget(self.pushButton_13)
        self.verticalLayout_17.setStretch(0, 1)
        self.verticalLayout_17.setStretch(1, 2)
        self.verticalLayout_17.setStretch(2, 2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_17)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setSpacing(10)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_7 = QtWidgets.QLabel(self.group_single)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_18.addWidget(self.label_7)
        self.pushButton_14 = QtWidgets.QPushButton(self.group_single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_14.sizePolicy().hasHeightForWidth())
        self.pushButton_14.setSizePolicy(sizePolicy)
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_18.addWidget(self.pushButton_14)
        self.pushButton_15 = QtWidgets.QPushButton(self.group_single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_15.sizePolicy().hasHeightForWidth())
        self.pushButton_15.setSizePolicy(sizePolicy)
        self.pushButton_15.setObjectName("pushButton_15")
        self.verticalLayout_18.addWidget(self.pushButton_15)
        self.verticalLayout_18.setStretch(0, 1)
        self.verticalLayout_18.setStretch(1, 2)
        self.verticalLayout_18.setStretch(2, 2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_18)
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setSpacing(10)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label_15 = QtWidgets.QLabel(self.group_single)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_27.addWidget(self.label_15)
        self.pushButton_30 = QtWidgets.QPushButton(self.group_single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_30.sizePolicy().hasHeightForWidth())
        self.pushButton_30.setSizePolicy(sizePolicy)
        self.pushButton_30.setObjectName("pushButton_30")
        self.verticalLayout_27.addWidget(self.pushButton_30)
        self.pushButton_31 = QtWidgets.QPushButton(self.group_single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_31.sizePolicy().hasHeightForWidth())
        self.pushButton_31.setSizePolicy(sizePolicy)
        self.pushButton_31.setObjectName("pushButton_31")
        self.verticalLayout_27.addWidget(self.pushButton_31)
        self.verticalLayout_27.setStretch(0, 1)
        self.verticalLayout_27.setStretch(1, 2)
        self.verticalLayout_27.setStretch(2, 2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_27)
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setSpacing(10)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.label_16 = QtWidgets.QLabel(self.group_single)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_28.addWidget(self.label_16)
        self.pushButton_32 = QtWidgets.QPushButton(self.group_single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_32.sizePolicy().hasHeightForWidth())
        self.pushButton_32.setSizePolicy(sizePolicy)
        self.pushButton_32.setObjectName("pushButton_32")
        self.verticalLayout_28.addWidget(self.pushButton_32)
        self.pushButton_33 = QtWidgets.QPushButton(self.group_single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_33.sizePolicy().hasHeightForWidth())
        self.pushButton_33.setSizePolicy(sizePolicy)
        self.pushButton_33.setObjectName("pushButton_33")
        self.verticalLayout_28.addWidget(self.pushButton_33)
        self.verticalLayout_28.setStretch(0, 1)
        self.verticalLayout_28.setStretch(1, 2)
        self.verticalLayout_28.setStretch(2, 2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_28)
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setSpacing(10)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.label_17 = QtWidgets.QLabel(self.group_single)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_29.addWidget(self.label_17)
        self.pushButton_34 = QtWidgets.QPushButton(self.group_single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_34.sizePolicy().hasHeightForWidth())
        self.pushButton_34.setSizePolicy(sizePolicy)
        self.pushButton_34.setObjectName("pushButton_34")
        self.verticalLayout_29.addWidget(self.pushButton_34)
        self.pushButton_35 = QtWidgets.QPushButton(self.group_single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_35.sizePolicy().hasHeightForWidth())
        self.pushButton_35.setSizePolicy(sizePolicy)
        self.pushButton_35.setObjectName("pushButton_35")
        self.verticalLayout_29.addWidget(self.pushButton_35)
        self.verticalLayout_29.setStretch(0, 1)
        self.verticalLayout_29.setStretch(1, 2)
        self.verticalLayout_29.setStretch(2, 2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_29)
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setSpacing(10)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.label_18 = QtWidgets.QLabel(self.group_single)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_30.addWidget(self.label_18)
        self.pushButton_36 = QtWidgets.QPushButton(self.group_single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_36.sizePolicy().hasHeightForWidth())
        self.pushButton_36.setSizePolicy(sizePolicy)
        self.pushButton_36.setObjectName("pushButton_36")
        self.verticalLayout_30.addWidget(self.pushButton_36)
        self.pushButton_37 = QtWidgets.QPushButton(self.group_single)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_37.sizePolicy().hasHeightForWidth())
        self.pushButton_37.setSizePolicy(sizePolicy)
        self.pushButton_37.setObjectName("pushButton_37")
        self.verticalLayout_30.addWidget(self.pushButton_37)
        self.verticalLayout_30.setStretch(0, 1)
        self.verticalLayout_30.setStretch(1, 2)
        self.verticalLayout_30.setStretch(2, 2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_30)
        self.verticalLayout_22.addWidget(self.group_single)
        self.frame_7 = QtWidgets.QFrame(self.pg_control)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.group_hand = QtWidgets.QGroupBox(self.frame_7)
        self.group_hand.setObjectName("group_hand")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.group_hand)
        self.horizontalLayout_11.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_11.setSpacing(10)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setSpacing(10)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_8 = QtWidgets.QLabel(self.group_hand)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_24.addWidget(self.label_8)
        self.pushButton_16 = QtWidgets.QPushButton(self.group_hand)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_16.sizePolicy().hasHeightForWidth())
        self.pushButton_16.setSizePolicy(sizePolicy)
        self.pushButton_16.setObjectName("pushButton_16")
        self.verticalLayout_24.addWidget(self.pushButton_16)
        self.pushButton_17 = QtWidgets.QPushButton(self.group_hand)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_17.sizePolicy().hasHeightForWidth())
        self.pushButton_17.setSizePolicy(sizePolicy)
        self.pushButton_17.setObjectName("pushButton_17")
        self.verticalLayout_24.addWidget(self.pushButton_17)
        self.verticalLayout_24.setStretch(0, 1)
        self.verticalLayout_24.setStretch(1, 2)
        self.verticalLayout_24.setStretch(2, 2)
        self.horizontalLayout_11.addLayout(self.verticalLayout_24)
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setSpacing(10)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_9 = QtWidgets.QLabel(self.group_hand)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_25.addWidget(self.label_9)
        self.pushButton_18 = QtWidgets.QPushButton(self.group_hand)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_18.sizePolicy().hasHeightForWidth())
        self.pushButton_18.setSizePolicy(sizePolicy)
        self.pushButton_18.setObjectName("pushButton_18")
        self.verticalLayout_25.addWidget(self.pushButton_18)
        self.pushButton_19 = QtWidgets.QPushButton(self.group_hand)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_19.sizePolicy().hasHeightForWidth())
        self.pushButton_19.setSizePolicy(sizePolicy)
        self.pushButton_19.setObjectName("pushButton_19")
        self.verticalLayout_25.addWidget(self.pushButton_19)
        self.verticalLayout_25.setStretch(0, 1)
        self.verticalLayout_25.setStretch(1, 2)
        self.verticalLayout_25.setStretch(2, 2)
        self.horizontalLayout_11.addLayout(self.verticalLayout_25)
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setSpacing(10)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_10 = QtWidgets.QLabel(self.group_hand)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_26.addWidget(self.label_10)
        self.pushButton_20 = QtWidgets.QPushButton(self.group_hand)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_20.sizePolicy().hasHeightForWidth())
        self.pushButton_20.setSizePolicy(sizePolicy)
        self.pushButton_20.setObjectName("pushButton_20")
        self.verticalLayout_26.addWidget(self.pushButton_20)
        self.pushButton_21 = QtWidgets.QPushButton(self.group_hand)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_21.sizePolicy().hasHeightForWidth())
        self.pushButton_21.setSizePolicy(sizePolicy)
        self.pushButton_21.setObjectName("pushButton_21")
        self.verticalLayout_26.addWidget(self.pushButton_21)
        self.verticalLayout_26.setStretch(0, 1)
        self.verticalLayout_26.setStretch(1, 2)
        self.verticalLayout_26.setStretch(2, 2)
        self.horizontalLayout_11.addLayout(self.verticalLayout_26)
        self.verticalLayout_31 = QtWidgets.QVBoxLayout()
        self.verticalLayout_31.setSpacing(10)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.label_11 = QtWidgets.QLabel(self.group_hand)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_31.addWidget(self.label_11)
        self.pushButton_22 = QtWidgets.QPushButton(self.group_hand)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_22.sizePolicy().hasHeightForWidth())
        self.pushButton_22.setSizePolicy(sizePolicy)
        self.pushButton_22.setObjectName("pushButton_22")
        self.verticalLayout_31.addWidget(self.pushButton_22)
        self.pushButton_23 = QtWidgets.QPushButton(self.group_hand)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_23.sizePolicy().hasHeightForWidth())
        self.pushButton_23.setSizePolicy(sizePolicy)
        self.pushButton_23.setObjectName("pushButton_23")
        self.verticalLayout_31.addWidget(self.pushButton_23)
        self.verticalLayout_31.setStretch(0, 1)
        self.verticalLayout_31.setStretch(1, 2)
        self.verticalLayout_31.setStretch(2, 2)
        self.horizontalLayout_11.addLayout(self.verticalLayout_31)
        self.horizontalLayout_10.addWidget(self.group_hand)
        self.group_end = QtWidgets.QGroupBox(self.frame_7)
        self.group_end.setObjectName("group_end")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.group_end)
        self.horizontalLayout_12.setContentsMargins(5, 10, 0, 0)
        self.horizontalLayout_12.setSpacing(10)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setSpacing(10)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.label_12 = QtWidgets.QLabel(self.group_end)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_32.addWidget(self.label_12)
        self.pushButton_4 = QtWidgets.QPushButton(self.group_end)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_32.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.group_end)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_32.addWidget(self.pushButton_5)
        self.verticalLayout_32.setStretch(0, 1)
        self.verticalLayout_32.setStretch(1, 2)
        self.verticalLayout_32.setStretch(2, 2)
        self.horizontalLayout_12.addLayout(self.verticalLayout_32)
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setSpacing(10)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.label_13 = QtWidgets.QLabel(self.group_end)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_33.addWidget(self.label_13)
        self.pushButton_24 = QtWidgets.QPushButton(self.group_end)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_24.sizePolicy().hasHeightForWidth())
        self.pushButton_24.setSizePolicy(sizePolicy)
        self.pushButton_24.setObjectName("pushButton_24")
        self.verticalLayout_33.addWidget(self.pushButton_24)
        self.pushButton_26 = QtWidgets.QPushButton(self.group_end)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_26.sizePolicy().hasHeightForWidth())
        self.pushButton_26.setSizePolicy(sizePolicy)
        self.pushButton_26.setObjectName("pushButton_26")
        self.verticalLayout_33.addWidget(self.pushButton_26)
        self.verticalLayout_33.setStretch(0, 1)
        self.verticalLayout_33.setStretch(1, 2)
        self.verticalLayout_33.setStretch(2, 2)
        self.horizontalLayout_12.addLayout(self.verticalLayout_33)
        self.verticalLayout_34 = QtWidgets.QVBoxLayout()
        self.verticalLayout_34.setSpacing(10)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.label_14 = QtWidgets.QLabel(self.group_end)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_34.addWidget(self.label_14)
        self.pushButton_25 = QtWidgets.QPushButton(self.group_end)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_25.sizePolicy().hasHeightForWidth())
        self.pushButton_25.setSizePolicy(sizePolicy)
        self.pushButton_25.setObjectName("pushButton_25")
        self.verticalLayout_34.addWidget(self.pushButton_25)
        self.pushButton_27 = QtWidgets.QPushButton(self.group_end)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_27.sizePolicy().hasHeightForWidth())
        self.pushButton_27.setSizePolicy(sizePolicy)
        self.pushButton_27.setObjectName("pushButton_27")
        self.verticalLayout_34.addWidget(self.pushButton_27)
        self.verticalLayout_34.setStretch(0, 1)
        self.verticalLayout_34.setStretch(1, 2)
        self.verticalLayout_34.setStretch(2, 2)
        self.horizontalLayout_12.addLayout(self.verticalLayout_34)
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setSpacing(10)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.label_19 = QtWidgets.QLabel(self.group_end)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_35.addWidget(self.label_19)
        self.pushButton_28 = QtWidgets.QPushButton(self.group_end)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_28.sizePolicy().hasHeightForWidth())
        self.pushButton_28.setSizePolicy(sizePolicy)
        self.pushButton_28.setObjectName("pushButton_28")
        self.verticalLayout_35.addWidget(self.pushButton_28)
        self.pushButton_39 = QtWidgets.QPushButton(self.group_end)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_39.sizePolicy().hasHeightForWidth())
        self.pushButton_39.setSizePolicy(sizePolicy)
        self.pushButton_39.setObjectName("pushButton_39")
        self.verticalLayout_35.addWidget(self.pushButton_39)
        self.verticalLayout_35.setStretch(0, 1)
        self.verticalLayout_35.setStretch(1, 2)
        self.verticalLayout_35.setStretch(2, 2)
        self.horizontalLayout_12.addLayout(self.verticalLayout_35)
        self.verticalLayout_36 = QtWidgets.QVBoxLayout()
        self.verticalLayout_36.setSpacing(10)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.label_20 = QtWidgets.QLabel(self.group_end)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_36.addWidget(self.label_20)
        self.pushButton_29 = QtWidgets.QPushButton(self.group_end)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_29.sizePolicy().hasHeightForWidth())
        self.pushButton_29.setSizePolicy(sizePolicy)
        self.pushButton_29.setObjectName("pushButton_29")
        self.verticalLayout_36.addWidget(self.pushButton_29)
        self.pushButton_40 = QtWidgets.QPushButton(self.group_end)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_40.sizePolicy().hasHeightForWidth())
        self.pushButton_40.setSizePolicy(sizePolicy)
        self.pushButton_40.setObjectName("pushButton_40")
        self.verticalLayout_36.addWidget(self.pushButton_40)
        self.verticalLayout_36.setStretch(0, 1)
        self.verticalLayout_36.setStretch(1, 2)
        self.verticalLayout_36.setStretch(2, 2)
        self.horizontalLayout_12.addLayout(self.verticalLayout_36)
        self.verticalLayout_37 = QtWidgets.QVBoxLayout()
        self.verticalLayout_37.setSpacing(10)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.label_21 = QtWidgets.QLabel(self.group_end)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_37.addWidget(self.label_21)
        self.pushButton_38 = QtWidgets.QPushButton(self.group_end)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_38.sizePolicy().hasHeightForWidth())
        self.pushButton_38.setSizePolicy(sizePolicy)
        self.pushButton_38.setObjectName("pushButton_38")
        self.verticalLayout_37.addWidget(self.pushButton_38)
        self.pushButton_41 = QtWidgets.QPushButton(self.group_end)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_41.sizePolicy().hasHeightForWidth())
        self.pushButton_41.setSizePolicy(sizePolicy)
        self.pushButton_41.setObjectName("pushButton_41")
        self.verticalLayout_37.addWidget(self.pushButton_41)
        self.verticalLayout_37.setStretch(0, 1)
        self.verticalLayout_37.setStretch(1, 2)
        self.verticalLayout_37.setStretch(2, 2)
        self.horizontalLayout_12.addLayout(self.verticalLayout_37)
        self.horizontalLayout_10.addWidget(self.group_end)
        self.verticalLayout_22.addWidget(self.frame_7)
        self.verticalLayout_22.setStretch(0, 1)
        self.verticalLayout_22.setStretch(1, 1)
        self.verticalLayout_22.setStretch(2, 1)
        self.stackedWidget.addWidget(self.pg_control)
        self.pg_log = QtWidgets.QWidget()
        self.pg_log.setObjectName("pg_log")
        self.verticalLayout_49 = QtWidgets.QVBoxLayout(self.pg_log)
        self.verticalLayout_49.setObjectName("verticalLayout_49")
        self.groupBox_4 = QtWidgets.QGroupBox(self.pg_log)
        self.groupBox_4.setObjectName("groupBox_4")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton.setGeometry(QtCore.QRect(40, 50, 201, 211))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_42 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_42.setGeometry(QtCore.QRect(480, 60, 261, 181))
        self.pushButton_42.setObjectName("pushButton_42")
        self.verticalLayout_49.addWidget(self.groupBox_4)
        self.groupBox_9 = QtWidgets.QGroupBox(self.pg_log)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_49.addWidget(self.groupBox_9)
        self.groupBox_10 = QtWidgets.QGroupBox(self.pg_log)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_49.addWidget(self.groupBox_10)
        self.stackedWidget.addWidget(self.pg_log)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.frame_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 8)
        MainWindow.setCentralWidget(self.control_window)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "龙骨式连续体机器人操作软件"))
        self.bt_init.setText(_translate("MainWindow", "初始化"))
        self.bt_control.setText(_translate("MainWindow", "操作面板"))
        self.bt_log.setText(_translate("MainWindow", "机器人状态"))
        self.group_usbcan.setTitle(_translate("MainWindow", "【USBCAN卡】"))
        self.bt_open.setText(_translate("MainWindow", "打开"))
        self.bx_rate0.setItemText(0, _translate("MainWindow", "250K"))
        self.bx_rate1.setItemText(0, _translate("MainWindow", "250K"))
        self.bt_channel0.setText(_translate("MainWindow", "打开0"))
        self.bt_channel1.setText(_translate("MainWindow", "打开1"))
        self.bt_reset0.setText(_translate("MainWindow", "重置0"))
        self.bt_reset1.setText(_translate("MainWindow", "重置1"))
        self.bt_close.setText(_translate("MainWindow", "关闭"))
        self.group_motor.setTitle(_translate("MainWindow", "【电机】"))
        self.check_all.setText(_translate("MainWindow", "一键检查电机"))
        self.start.setText(_translate("MainWindow", "启动PDO"))
        self.check_1.setText(_translate("MainWindow", "M1"))
        self.check_2.setText(_translate("MainWindow", "M2"))
        self.check_3.setText(_translate("MainWindow", "M3"))
        self.check_4.setText(_translate("MainWindow", "M4"))
        self.check_5.setText(_translate("MainWindow", "M5"))
        self.check_6.setText(_translate("MainWindow", "M6"))
        self.check_7.setText(_translate("MainWindow", "M7"))
        self.check_8.setText(_translate("MainWindow", "M8"))
        self.check_9.setText(_translate("MainWindow", "M9"))
        self.check_10.setText(_translate("MainWindow", "M10"))
        self.r_pos.setText(_translate("MainWindow", "位置模式"))
        self.r_vel.setText(_translate("MainWindow", "速度模式"))
        self.tx_acc.setText(_translate("MainWindow", "加速度"))
        self.le_acc.setPlaceholderText(_translate("MainWindow", "1000"))
        self.tx_dec.setText(_translate("MainWindow", "减速度"))
        self.le_dec.setPlaceholderText(_translate("MainWindow", "10000"))
        self.tx_vel.setText(_translate("MainWindow", "动作速度"))
        self.le_vel.setPlaceholderText(_translate("MainWindow", "100"))
        self.tx_position.setText(_translate("MainWindow", "运动间隔"))
        self.le_position.setPlaceholderText(_translate("MainWindow", "50"))
        self.tx_inhibit.setText(_translate("MainWindow", "禁止时间"))
        self.le_inhibit.setPlaceholderText(_translate("MainWindow", "500"))
        self.bt_save.setText(_translate("MainWindow", "保存"))
        self.bt_launch.setText(_translate("MainWindow", "生效"))
        self.group_io.setTitle(_translate("MainWindow", "【IO设备】"))
        self.bt_check.setText(_translate("MainWindow", "检查耦合器"))
        self.bt_start.setText(_translate("MainWindow", "启动RPDO"))
        self.groupBox_7.setTitle(_translate("MainWindow", "力传感器数据采集卡"))
        self.group_status.setTitle(_translate("MainWindow", "状态控制"))
        self.bt_quick_stop.setText(_translate("MainWindow", "急停"))
        self.bt_unlock_all.setText(_translate("MainWindow", "解除所有抱闸"))
        self.bt_unlock_1.setText(_translate("MainWindow", "1"))
        self.bt_unlock_2.setText(_translate("MainWindow", "2"))
        self.bt_unlock_3.setText(_translate("MainWindow", "3"))
        self.bt_unlock_4.setText(_translate("MainWindow", "4"))
        self.bt_unlock_5.setText(_translate("MainWindow", "5"))
        self.bt_unlock_6.setText(_translate("MainWindow", "6"))
        self.bt_unlock_7.setText(_translate("MainWindow", "7"))
        self.bt_unlock_8.setText(_translate("MainWindow", "8"))
        self.bt_unlock_9.setText(_translate("MainWindow", "9"))
        self.bt_unlock_10.setText(_translate("MainWindow", "10"))
        self.bt_enable.setText(_translate("MainWindow", "使能"))
        self.group_single.setTitle(_translate("MainWindow", "单电机操作"))
        self.label.setText(_translate("MainWindow", "1"))
        self.pushButton_2.setText(_translate("MainWindow", "+"))
        self.pushButton_3.setText(_translate("MainWindow", "-"))
        self.label_3.setText(_translate("MainWindow", "2"))
        self.pushButton_6.setText(_translate("MainWindow", "+"))
        self.pushButton_7.setText(_translate("MainWindow", "-"))
        self.label_4.setText(_translate("MainWindow", "3"))
        self.pushButton_8.setText(_translate("MainWindow", "+"))
        self.pushButton_9.setText(_translate("MainWindow", "-"))
        self.label_5.setText(_translate("MainWindow", "4"))
        self.pushButton_10.setText(_translate("MainWindow", "+"))
        self.pushButton_11.setText(_translate("MainWindow", "-"))
        self.label_6.setText(_translate("MainWindow", "5"))
        self.pushButton_12.setText(_translate("MainWindow", "+"))
        self.pushButton_13.setText(_translate("MainWindow", "-"))
        self.label_7.setText(_translate("MainWindow", "6"))
        self.pushButton_14.setText(_translate("MainWindow", "+"))
        self.pushButton_15.setText(_translate("MainWindow", "-"))
        self.label_15.setText(_translate("MainWindow", "7"))
        self.pushButton_30.setText(_translate("MainWindow", "+"))
        self.pushButton_31.setText(_translate("MainWindow", "-"))
        self.label_16.setText(_translate("MainWindow", "8"))
        self.pushButton_32.setText(_translate("MainWindow", "+"))
        self.pushButton_33.setText(_translate("MainWindow", "-"))
        self.label_17.setText(_translate("MainWindow", "9"))
        self.pushButton_34.setText(_translate("MainWindow", "+"))
        self.pushButton_35.setText(_translate("MainWindow", "-"))
        self.label_18.setText(_translate("MainWindow", "10"))
        self.pushButton_36.setText(_translate("MainWindow", "+"))
        self.pushButton_37.setText(_translate("MainWindow", "-"))
        self.group_hand.setTitle(_translate("MainWindow", "单电磁阀操作"))
        self.label_8.setText(_translate("MainWindow", "1"))
        self.pushButton_16.setText(_translate("MainWindow", "ON"))
        self.pushButton_17.setText(_translate("MainWindow", "OFF"))
        self.label_9.setText(_translate("MainWindow", "2"))
        self.pushButton_18.setText(_translate("MainWindow", "ON"))
        self.pushButton_19.setText(_translate("MainWindow", "OFF"))
        self.label_10.setText(_translate("MainWindow", "3"))
        self.pushButton_20.setText(_translate("MainWindow", "ON"))
        self.pushButton_21.setText(_translate("MainWindow", "OFF"))
        self.label_11.setText(_translate("MainWindow", "4"))
        self.pushButton_22.setText(_translate("MainWindow", "ON"))
        self.pushButton_23.setText(_translate("MainWindow", "OFF"))
        self.group_end.setTitle(_translate("MainWindow", "末端操作"))
        self.label_12.setText(_translate("MainWindow", "X方向"))
        self.pushButton_4.setText(_translate("MainWindow", "+"))
        self.pushButton_5.setText(_translate("MainWindow", "-"))
        self.label_13.setText(_translate("MainWindow", "Y方向"))
        self.pushButton_24.setText(_translate("MainWindow", "+"))
        self.pushButton_26.setText(_translate("MainWindow", "-"))
        self.label_14.setText(_translate("MainWindow", "Z方向"))
        self.pushButton_25.setText(_translate("MainWindow", "+"))
        self.pushButton_27.setText(_translate("MainWindow", "-"))
        self.label_19.setText(_translate("MainWindow", "X轴"))
        self.pushButton_28.setText(_translate("MainWindow", "顺"))
        self.pushButton_39.setText(_translate("MainWindow", "逆"))
        self.label_20.setText(_translate("MainWindow", "Y轴"))
        self.pushButton_29.setText(_translate("MainWindow", "顺"))
        self.pushButton_40.setText(_translate("MainWindow", "逆"))
        self.label_21.setText(_translate("MainWindow", "Z轴"))
        self.pushButton_38.setText(_translate("MainWindow", "顺"))
        self.pushButton_41.setText(_translate("MainWindow", "逆"))
        self.groupBox_4.setTitle(_translate("MainWindow", "设置"))
        self.pushButton.setText(_translate("MainWindow", "更新所有状态"))
        self.pushButton_42.setText(_translate("MainWindow", "关闭电机状态反馈"))
        self.groupBox_9.setTitle(_translate("MainWindow", "连续体"))
        self.groupBox_10.setTitle(_translate("MainWindow", "气动夹爪"))
